import { Document, Page, Text, View, StyleSheet, Image, pdf } from "@react-pdf/renderer";
import type { FiatScenarioSnapshot, ClientInfo } from "@/context/PlannerContext";
import { WEIGHTS } from "@/lib/scoring/weights";

const REFERENCE_SCENARIO_NOTE =
  "This is an illustrative benchmark generated by the DCC scoring engine. It is not a personalised recommendation. Define your own scenario in the My Scenario tab before acting.";
const MY_SCENARIO_NOTE =
  "You are building this scenario. All allocation weights, provider selections, and inputs are your own choices. DCC provides scoring data only.";

const DISCLAIMERS = [
  "This document is a scenario analysis output produced by DCC's deterministic scoring engine for informational purposes only. It does not constitute investment, financial, legal, or tax advice. It is not a regulated suitability assessment under any applicable financial services law. DCC is not a licensed investment adviser, financial adviser, broker-dealer, or credit rating agency in any jurisdiction. No fiduciary duty is created by the production or delivery of this document. This document must not be relied upon as the sole basis for any investment decision.",
  "DCC scores are computed solely from publicly available information as of the date shown. They do not incorporate private issuer disclosures, audited financial data, or undisclosed material information. Where data gaps exist, scores reflect available evidence only; the absence of information may itself indicate a risk factor. Scores are not predictions of future performance, creditworthiness, or default probability.",
  "All scenario outputs — including yield estimates, income projections, BTC collateral requirements, liquidation price thresholds, margin call trigger prices, LTV calculations, interest computations, Scenario Risk Index (SRI) values, Reference Scenario allocation weights, and blended APY figures — are illustrative and scenario-specific. They are computed from user-supplied inputs and DCC scoring data as of the date shown. Actual outcomes may differ materially. These figures do not constitute a guarantee, warranty, or representation as to actual outcomes.",
  "Digital Credit Compass is not a registered investment adviser, broker-dealer, or financial institution.",
  "Past performance is not a reliable indicator of future results. Past DCC scores, provider track records, yield histories, and prior methodology versions do not guarantee, predict, or suggest future scoring outcomes, yields, or investment performance.",
  "Users are solely responsible for their own investment decisions. DCC's liability, where permitted by applicable law, is limited to direct losses caused solely by a material error in the DCC scoring engine demonstrably attributable to DCC. DCC shall not be liable for indirect, consequential, speculative, or punitive losses. Nothing in this document limits any statutory rights you may have under applicable consumer protection or financial services law that cannot be excluded by agreement.",
  "This report does not constitute a solicitation or offer to buy or sell any financial instrument or product.",
];

const FIAT_COLOR = "#4F46E5";

const FIAT_CRITERIA_LABELS: Record<string, string> = {
  marketVolatility: "Market Volatility",
  incomeMechanism: "Income Mechanism",
  seniority: "Seniority",
  complexity: "Complexity",
  providerQuality: "Provider Quality",
};

const S = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 9,
    color: "#1A1714",
    backgroundColor: "#FFFFFF",
    padding: 40,
  },
  accentBar: {
    backgroundColor: FIAT_COLOR,
    height: 4,
    marginBottom: 20,
    borderRadius: 2,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  reportTitle: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    color: "#1A1714",
  },
  reportSubtitle: {
    fontSize: 8,
    color: "#9C9488",
    marginTop: 3,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  reportMeta: {
    fontSize: 7.5,
    color: "#9C9488",
    textAlign: "right",
  },
  clientCard: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: "#F5F4F0",
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  clientField: { flex: 1 },
  clientLabel: {
    fontSize: 7,
    color: "#9C9488",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  clientValue: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: "#1A1714",
  },
  section: { marginBottom: 16 },
  sectionTitle: {
    fontSize: 7.5,
    fontFamily: "Helvetica-Bold",
    color: "#9C9488",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 8,
    paddingBottom: 4,
    borderBottom: "1px solid #E0DBD3",
  },
  row2: { flexDirection: "row", gap: 10, marginBottom: 8 },
  statCell: {
    flex: 1,
    backgroundColor: "#F5F4F0",
    borderRadius: 6,
    padding: 10,
    borderLeft: "3px solid #4F46E5",
  },
  statLabel: {
    fontSize: 7,
    color: "#9C9488",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  statValue: {
    fontSize: 15,
    fontFamily: "Helvetica-Bold",
    color: FIAT_COLOR,
  },
  statSub: { fontSize: 7, color: "#9C9488", marginTop: 2 },
  allocationNote: { fontSize: 6, color: "#9C9488", marginTop: 4, lineHeight: 1.3, textAlign: "justify" },
  greenValue: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: "#059669",
  },
  tableHeader: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "nowrap",
    backgroundColor: "#F5F4F0",
    padding: "4 5",
    borderRadius: 4,
    marginBottom: 2,
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "nowrap",
    padding: "4 5",
    borderBottom: "1px solid #F0EDE8",
  },
  tableRowAlt: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "nowrap",
    padding: "4 5",
    backgroundColor: "#FAFAF8",
    borderBottom: "1px solid #F0EDE8",
  },
  th: {
    fontSize: 6,
    color: "#9C9488",
    fontFamily: "Helvetica-Bold",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  td: { fontSize: 7, color: "#1A1714" },
  tdBold: { fontSize: 7, color: "#1A1714", fontFamily: "Helvetica-Bold" },
  tdFiat: { fontSize: 7, color: FIAT_COLOR, fontFamily: "Helvetica-Bold" },
  tdGreen: { fontSize: 7, color: "#059669", fontFamily: "Helvetica-Bold" },
  tdWarn: { fontSize: 7, color: "#DC2626", fontFamily: "Helvetica-Bold" },
  disclaimerBox: {
    backgroundColor: "#F5F4F0",
    borderRadius: 6,
    padding: 12,
    marginTop: 16,
    borderLeft: "3px solid #E0DBD3",
  },
  disclaimerTitle: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: "#9C9488",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  disclaimerItem: {
    fontSize: 7,
    color: "#5C564E",
    marginBottom: 4,
    lineHeight: 1.5,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTop: "1px solid #E0DBD3",
    paddingTop: 8,
  },
  footerText: { fontSize: 7, color: "#9C9488" },
  hv30Warn: {
    backgroundColor: "#FEF3C7",
    borderRadius: 6,
    padding: 8,
    borderLeft: "3px solid #D97706",
    marginTop: 8,
  },
  criteriaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
    gap: 8,
  },
  criteriaLabel: { fontSize: 8, color: "#5C564E", width: 100 },
  criteriaBarBg: { width: 180, height: 6, backgroundColor: "#E0DBD3", borderRadius: 3 },
  criteriaBarFill: { height: 6, borderRadius: 3, backgroundColor: FIAT_COLOR },
  criteriaPct: { fontSize: 8, fontFamily: "Helvetica-Bold", color: "#1A1714", width: 28, textAlign: "right" },
  // Cover page
  coverPage: {
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#1A1714",
    backgroundColor: "#FFFFFF",
    padding: 48,
    flexDirection: "column",
    justifyContent: "space-between",
  },
  coverAccentBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 8,
    backgroundColor: FIAT_COLOR,
  },
  coverLogo: {
    marginTop: 20,
    marginBottom: 28,
    width: 127,
    height: 54,
    objectFit: "contain",
  },
  coverBrand: {
    fontSize: 9,
    letterSpacing: 3,
    color: "#9C9488",
    textTransform: "uppercase",
    marginBottom: 24,
  },
  coverTitle: {
    fontSize: 28,
    fontFamily: "Helvetica-Bold",
    color: "#1A1714",
    marginBottom: 8,
  },
  coverSubtitle: {
    fontSize: 11,
    color: "#5C564E",
    letterSpacing: 0.5,
    marginBottom: 48,
  },
  coverDivider: {
    width: 80,
    height: 2,
    backgroundColor: FIAT_COLOR,
    marginBottom: 32,
  },
  coverFieldLabel: {
    fontSize: 8,
    color: "#9C9488",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  coverFieldValue: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: "#1A1714",
    marginBottom: 20,
  },
  coverDisclaimerBlock: {
    marginTop: 6,
    marginBottom: 4,
  },
  coverDisclaimerTitle: {
    fontSize: 6,
    fontFamily: "Helvetica-Bold",
    color: "#1A1714",
    marginBottom: 2,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  coverDisclaimerText: {
    fontSize: 6,
    color: "#5C564E",
    lineHeight: 1.35,
    textAlign: "justify",
  },
  coverFooter: {
    fontSize: 7,
    color: "#9C9488",
    marginTop: 24,
    paddingTop: 24,
    borderTop: "1px solid #E0DBD3",
  },
});

function fmt(n: number) {
  return "$" + Math.round(n).toLocaleString("en-US");
}

export function FiatPdfDocument({
  snapshot,
  client,
  logoSrc,
}: {
  snapshot: FiatScenarioSnapshot;
  client: ClientInfo;
  logoSrc?: string;
}) {
  const { inputs, results, instruments, blendedApy, allocationWeights, savedAt } = snapshot;
  const dateStr = new Date(savedAt).toLocaleDateString("en-GB", {
    day: "2-digit", month: "short", year: "numeric",
  });
  const timeStr = new Date(savedAt).toLocaleTimeString("en-GB", {
    hour: "2-digit", minute: "2-digit",
  });
  const hasHv30Warning = instruments.some(i => i.hv30 > 35);
  const reportRef = savedAt.replace(/\D/g, "").slice(0, 14);

  const incomeShare = (ticker: string) => {
    const w = (allocationWeights && allocationWeights[ticker]) ?? 0;
    const pct = w / 100;
    return {
      annualMin: results.annualMin * pct,
      annualMax: results.annualMax * pct,
      totalMin: results.totalMin * pct,
      totalMax: results.totalMax * pct,
    };
  };

  return (
    <Document>
      <Page size="A4" style={S.coverPage}>
        <View style={S.coverAccentBar} />
        <View>
          {logoSrc ? <Image src={logoSrc} style={S.coverLogo} /> : null}
          <Text style={S.coverBrand}>Digital Credit Compass</Text>
          <Text style={S.coverTitle}>Risk Analysis Report</Text>
          <Text style={S.coverSubtitle}>Fiat Income Planner</Text>
          <View style={S.coverDivider} />
          <Text style={S.coverFieldLabel}>Prepared for</Text>
          <Text style={S.coverFieldValue}>{client.clientName || "—"}</Text>
          <Text style={S.coverFieldLabel}>Report date</Text>
          <Text style={S.coverFieldValue}>{dateStr}</Text>
          <Text style={S.coverFieldLabel}>Reference</Text>
          <Text style={S.coverFieldValue}>DCC-{reportRef}</Text>
        </View>
        <View style={S.coverDisclaimerBlock}>
          <Text style={S.coverDisclaimerTitle}>IMPORTANT:</Text>
          <Text style={S.coverDisclaimerText}>
            This document is a scenario analysis output only. It does not constitute investment, financial, legal, or tax advice and is not a regulated suitability assessment under any applicable law. All figures, scores, projected income, liquidation prices, collateral calculations, and allocation outputs are illustrative only. The Reference Scenario is an engine-generated benchmark — it is not a personalised recommendation. You must construct your own scenario before making any investment decision. Consult a qualified licensed financial adviser.
          </Text>
        </View>
        <View style={S.coverDisclaimerBlock}>
          <Text style={S.coverDisclaimerTitle}>NO CONFLICTS OF INTEREST:</Text>
          <Text style={S.coverDisclaimerText}>
            DCC does not accept payment from any provider, issuer, or platform in connection with the production or modification of any score. No DCC score is influenced by commercial relationships or issuer-paid engagement. All scores are computed from publicly available information via a deterministic scoring engine. DCC holds no financial interest in any instrument, provider, or allocation shown in this document.
          </Text>
        </View>
        <View style={S.coverDisclaimerBlock}>
          <Text style={S.coverDisclaimerTitle}>REGULATORY STATUS:</Text>
          <Text style={S.coverDisclaimerText}>
            Digital Credit Compass is not authorised or regulated by the FCA (UK), SEC (USA), MAS (Singapore), ESMA (EU), VARA (UAE), or any other financial services regulatory body. This document has not been approved by an FCA-authorised person under s.21 FSMA 2000. It is not directed at retail clients in the United Kingdom. Recipients in regulated jurisdictions must seek independent legal and regulatory advice before acting on any information herein.
          </Text>
        </View>
        <Text style={S.coverFooter}>
          Confidential — For the addressee only. This report is for informational purposes and does not constitute investment advice. DCC v1.0 · Deterministic (Methodology v1.0) · Append-only versioning.
        </Text>
      </Page>

      <Page size="A4" style={S.page}>
        <View style={S.accentBar} />

        {/* HEADER */}
        <View style={S.headerRow}>
          <View>
            <Text style={S.reportTitle}>Risk Analysis Report</Text>
            <Text style={S.reportSubtitle}>Fiat Income Planner · DCC v1.0</Text>
          </View>
          <View>
            <Text style={S.reportMeta}>Generated: {dateStr} at {timeStr}</Text>
            <Text style={S.reportMeta}>Report ID: {savedAt.replace(/\D/g, "").slice(0, 14)}</Text>
            <Text style={S.reportMeta}>Allocation mode: {inputs.mode === "guided" ? "Reference Scenario (Illustrative)" : "My Scenario"}</Text>
          </View>
        </View>

        {/* CLIENT */}
        <View style={S.clientCard}>
          <View style={S.clientField}>
            <Text style={S.clientLabel}>Client</Text>
            <Text style={S.clientValue}>{client.clientName}</Text>
          </View>
          <View style={S.clientField}>
            <Text style={S.clientLabel}>Risk Preference</Text>
            <Text style={S.clientValue}>{client.riskPreference}</Text>
          </View>
          <View style={S.clientField}>
            <Text style={S.clientLabel}>Module</Text>
            <Text style={S.clientValue}>Fiat Income</Text>
          </View>
          <View style={S.clientField}>
            <Text style={S.clientLabel}>Data as of</Text>
            <Text style={S.clientValue}>{dateStr}</Text>
          </View>
        </View>

        {/* INPUTS */}
        <View style={S.section}>
          <Text style={S.sectionTitle}>Scenario Inputs</Text>
          <View style={S.row2}>
            <View style={S.statCell}>
              <Text style={S.statLabel}>Capital</Text>
              <Text style={S.statValue}>{fmt(inputs.capital)}</Text>
            </View>
            <View style={S.statCell}>
              <Text style={S.statLabel}>Duration</Text>
              <Text style={S.statValue}>{inputs.durationMonths} months</Text>
            </View>
            <View style={S.statCell}>
              <Text style={S.statLabel}>Allocation mode</Text>
              <Text style={S.statValue}>{inputs.mode === "guided" ? "Reference Scenario (Illustrative)" : "My Scenario"}</Text>
              <Text style={S.statSub}>
                {inputs.mode === "guided" ? "Top 3 by score, 60% / 20% / 20%" : "User-selected instruments & weights"}
              </Text>
              <Text style={S.allocationNote}>
                {inputs.mode === "guided" ? REFERENCE_SCENARIO_NOTE : MY_SCENARIO_NOTE}
              </Text>
            </View>
            <View style={S.statCell}>
              <Text style={S.statLabel}>Blended APY</Text>
              <Text style={S.statValue}>
                {blendedApy.min === blendedApy.max
                  ? `${blendedApy.min}%`
                  : `${blendedApy.min}% – ${blendedApy.max}%`}
              </Text>
            </View>
            <View style={S.statCell}>
              <Text style={S.statLabel}>Instruments</Text>
              <Text style={S.statValue}>{inputs.selectedTickers.join(", ")}</Text>
            </View>
          </View>
        </View>

        {/* SCORING CRITERIA */}
        <View style={S.section}>
          <Text style={S.sectionTitle}>Scoring Criteria</Text>
          {Object.entries(WEIGHTS.FIAT).map(([key, weight]) => (
            <View key={key} style={S.criteriaRow}>
              <Text style={S.criteriaLabel}>{FIAT_CRITERIA_LABELS[key] ?? key}</Text>
              <View style={S.criteriaBarBg}>
                <View style={[S.criteriaBarFill, { width: `${weight * 100}%` }]} />
              </View>
              <Text style={S.criteriaPct}>{(weight * 100).toFixed(0)}%</Text>
            </View>
          ))}
        </View>

        {/* PROJECTED INCOME */}
        <View style={S.section}>
          <Text style={S.sectionTitle}>Projected Income</Text>
          <View style={S.row2}>
            <View style={[S.statCell, { borderLeftColor: "#059669" }]}>
              <Text style={S.statLabel}>Annual Min</Text>
              <Text style={S.greenValue}>{fmt(results.annualMin)}</Text>
              <Text style={S.statSub}>at {blendedApy.min}% APY</Text>
            </View>
            <View style={[S.statCell, { borderLeftColor: "#059669" }]}>
              <Text style={S.statLabel}>Annual Max</Text>
              <Text style={S.greenValue}>{fmt(results.annualMax)}</Text>
              <Text style={S.statSub}>at {blendedApy.max}% APY</Text>
            </View>
            <View style={S.statCell}>
              <Text style={S.statLabel}>Monthly Min</Text>
              <Text style={S.statValue}>{fmt(results.monthlyMin)}</Text>
            </View>
            <View style={S.statCell}>
              <Text style={S.statLabel}>Monthly Max</Text>
              <Text style={S.statValue}>{fmt(results.monthlyMax)}</Text>
            </View>
          </View>
          <View style={S.row2}>
            <View style={[S.statCell, { borderLeftColor: "#7C3AED" }]}>
              <Text style={S.statLabel}>Total over {inputs.durationMonths}m (Min)</Text>
              <Text style={[S.statValue, { color: "#7C3AED" }]}>{fmt(results.totalMin)}</Text>
              <Text style={S.statSub}>Pro-rated on duration</Text>
            </View>
            <View style={[S.statCell, { borderLeftColor: "#7C3AED" }]}>
              <Text style={S.statLabel}>Total over {inputs.durationMonths}m (Max)</Text>
              <Text style={[S.statValue, { color: "#7C3AED" }]}>{fmt(results.totalMax)}</Text>
              <Text style={S.statSub}>Pro-rated on duration</Text>
            </View>
          </View>
        </View>

        {/* INSTRUMENTS TABLE */}
        <View style={S.section}>
          <Text style={S.sectionTitle}>
            Selected Instruments — DCC Scores (×{instruments[0]?.multiplier.toFixed(2) ?? "1.00"} duration adj.)
            {inputs.mode === "guided" ? " · Reference Scenario (60% / 20% / 20%)" : " · My Scenario allocation"}
          </Text>
          <View style={S.tableHeader}>
            <Text style={[S.th, { flex: 1.2 }]}>Instrument</Text>
            {allocationWeights && Object.keys(allocationWeights).length > 0 ? (
              <Text style={[S.th, { flex: 0.5 }]}>W%</Text>
            ) : null}
            <Text style={[S.th, { flex: 0.4 }]}>Raw</Text>
            <Text style={[S.th, { flex: 0.4 }]}>Adj</Text>
            <Text style={[S.th, { flex: 0.45 }]}>APY</Text>
            <Text style={[S.th, { flex: 0.4 }]}>HV30</Text>
            <Text style={[S.th, { flex: 1 }]}>Ann.</Text>
            <Text style={[S.th, { flex: 1 }]}>Total</Text>
            <Text style={[S.th, { flex: 0.6 }]}>Risk</Text>
          </View>
          {instruments.map((inst, i) => {
            const w = allocationWeights?.[inst.ticker] ?? 0;
            const share = incomeShare(inst.ticker);
            const annualStr = w <= 0 ? "—" : share.annualMin === share.annualMax
              ? fmt(share.annualMin)
              : `${fmt(share.annualMin)}–${fmt(share.annualMax)}`;
            const totalStr = w <= 0 ? "—" : share.totalMin === share.totalMax
              ? fmt(share.totalMin)
              : `${fmt(share.totalMin)}–${fmt(share.totalMax)}`;
            return (
              <View key={i} style={i % 2 === 0 ? S.tableRow : S.tableRowAlt}>
                <Text style={[S.tdBold, { flex: 1.2 }]}>{inst.ticker}</Text>
                {allocationWeights && Object.keys(allocationWeights).length > 0 ? (
                  <Text style={[S.td, { flex: 0.5 }]}>
                    {allocationWeights[inst.ticker] != null ? `${allocationWeights[inst.ticker].toFixed(0)}%` : "—"}
                  </Text>
                ) : null}
                <Text style={[S.td, { flex: 0.4 }]}>{inst.dccScore}</Text>
                <Text style={[S.tdFiat, { flex: 0.4 }]}>{inst.adjustedScore}</Text>
                <Text style={[S.tdGreen, { flex: 0.45 }]}>{inst.apyEstimate}%</Text>
                <Text style={[inst.hv30 > 35 ? S.tdWarn : S.td, { flex: 0.4 }]}>
                  {inst.hv30}%{inst.hv30 > 35 ? "⚠" : ""}
                </Text>
                <Text style={[S.tdGreen, { flex: 1 }]}>{annualStr}</Text>
                <Text style={[S.tdGreen, { flex: 1 }]}>{totalStr}</Text>
                <Text style={[S.td, { flex: 0.6 }]}>{inst.riskBand === "ELEVATED" ? "ELEV" : inst.riskBand}</Text>
              </View>
            );
          })}
        </View>

        {/* HV30 WARNING */}
        {hasHv30Warning && (
          <View style={S.hv30Warn}>
            <Text style={{ fontSize: 7.5, fontFamily: "Helvetica-Bold", color: "#D97706", marginBottom: 3 }}>
              ⚠ HV30 Hard Cap Rule Active
            </Text>
            <Text style={{ fontSize: 7.5, color: "#5C564E", lineHeight: 1.5 }}>
              One or more instruments exceed HV30 35% threshold.
              C1 (Market Volatility) is capped at 5/30 in the scoring engine,
              limiting maximum achievable DCC Score to approximately 58.
            </Text>
          </View>
        )}

        {/* DISCLAIMERS */}
        <View style={S.disclaimerBox}>
          <Text style={S.disclaimerTitle}>L E G A L   D I S C L A I M E R S</Text>
          {DISCLAIMERS.map((d, i) => (
            <Text key={i} style={S.disclaimerItem}>{i + 1}. {d}</Text>
          ))}
        </View>

        {/* FOOTER */}
        <View style={S.footer} fixed>
          <Text style={S.footerText}>DCC v1.0 · Fiat Income Planner · Scenario Output · Not a regulated suitability assessment</Text>
          <Text style={S.footerText}>Scores frozen at generation · {dateStr}</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function generateAndDownloadFiatPdf(
  snapshot: FiatScenarioSnapshot,
  client: ClientInfo
) {
  const blob = await pdf(
    <FiatPdfDocument snapshot={snapshot} client={client} logoSrc="/logo-dcc-pdf-cover.png" />
  ).toBlob();

  const clientSlug = client.clientName.replace(/\s+/g, "_").toLowerCase();
  const dateSlug   = new Date().toISOString().slice(0, 10);
  const filename   = `DCC_Report_1B_Fiat_${clientSlug}_${dateSlug}.pdf`;

  const url = URL.createObjectURL(blob);
  const a   = document.createElement("a");
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
