"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import type { StablecoinProto } from "@/types/planner";
import { useStablecoinPlanner } from "@/hooks/useStablecoinPlanner";
import { ClientInfoModal } from "@/components/planner/ClientInfoModal";
import { usePlannerContext } from "@/context/PlannerContext";
import type { ClientInfo, StablecoinScenarioSnapshot } from "@/context/PlannerContext";
import { useSession } from "@/hooks/useSession";
import { StatCard } from "@/components/ui/StatCard";
import { FormField } from "@/components/ui/FormField";
import { ResultCell } from "@/components/ui/ResultCell";
import { BreakdownBar } from "@/components/ui/BreakdownBar";
import { RiskBadge } from "@/components/ui/RiskBadge";
import { WEIGHTS } from "@/lib/scoring/weights";
import { AlertCircle, X } from "lucide-react";

const STBL = "#0891B2";
const DEFI_COLOR = "#0891B2";
const CEFI_COLOR = "#7C3AED";

function fmtApy(x: number): string {
  return Math.round(x) === x ? String(x) : x.toFixed(1);
}

const CRITERIA_LABELS: Record<string, string> = {
  reserveQuality: "Reserve Quality",
  yieldTransparency: "Yield Transparency",
  counterpartyRisk: "Counterparty Risk",
  liquidity: "Liquidity",
  jurisdiction: "Jurisdiction",
  trackRecord: "Track Record",
};

// Provider counts per proto for proto selector labels (DeFi / CeFi)
const ALL_PROVIDERS_COUNT: Partial<Record<StablecoinProto, { defi: number; cefi: number }>> = {
  USDC: { defi: 3, cefi: 2 },
  USDT: { defi: 4, cefi: 2 },
};

const REFERENCE_SCENARIO_TOOLTIP =
  "This is an illustrative benchmark generated by the DCC scoring engine. It is not a personalised recommendation. Define your own scenario in the My Scenario tab before acting.";

const MY_SCENARIO_TOOLTIP =
  "You are building this scenario. All allocation weights, provider selections, and inputs are your own choices. DCC provides scoring data only.";

function ProviderTable({
  title,
  badge,
  badgeColor,
  providers,
  multiplier,
  durationMonths,
  capitalPoche,
  weightPct,
  mode,
  weights,
  sum,
  isValid,
  onWeightChange,
}: {
  title: string;
  badge: string;
  badgeColor: string;
  providers: ReturnType<typeof useStablecoinPlanner>["adjustedDefi"];
  multiplier: number;
  durationMonths: number;
  capitalPoche: number;
  weightPct: number;
  mode: "guided" | "custom";
  weights: Record<string, number>;
  sum: number;
  isValid: boolean;
  onWeightChange: (name: string, pct: number) => void;
}) {
  const isCustom = mode === "custom";
  const chipColor = isValid ? "#059669" : sum > 100 ? "#DC2626" : "#D97706";

  return (
    <div className="bg-white border border-border rounded-xl shadow-sm overflow-hidden">
      <div className="flex items-center justify-between px-4 py-3.5 border-b border-border">
        <div>
          <div className="font-display font-semibold text-[13px]">{title}</div>
          <div className="font-mono text-[9px] text-text-muted mt-0.5">
            {weightPct}% of capital · $
            {Math.round(capitalPoche).toLocaleString("en-US", { maximumFractionDigits: 0 })} ·
            ×{multiplier.toFixed(2)}
          </div>
        </div>
        <div className="flex items-center gap-2">
          {isCustom && (
            <span
              className="font-mono text-[9px] px-2 py-0.5 rounded-lg border font-bold"
              style={{
                background: chipColor + "15",
                color: chipColor,
                borderColor: chipColor + "40",
              }}
            >
              ∑ {sum.toFixed(1)}%
            </span>
          )}
          <span
            className="font-mono text-[8.5px] px-2 py-0.5 rounded border font-semibold"
            style={{
              background: badgeColor + "15",
              color: badgeColor,
              borderColor: badgeColor + "40",
            }}
          >
            {badge}
          </span>
        </div>
      </div>

      {isCustom && !isValid && sum > 0 && (
        <div
          className="px-4 py-2 border-b border-border font-mono text-[9px]"
          style={{ background: chipColor + "08", color: chipColor }}
        >
          {sum > 100
            ? `⚠ Total exceeds 100% — reduce by ${(sum - 100).toFixed(1)}%`
            : `⚠ Total at ${sum.toFixed(1)}% — ${(100 - sum).toFixed(1)}% remaining to allocate`}
        </div>
      )}

      {providers.length === 0 ? (
        <div className="px-4 py-6 text-center font-mono text-[11px] text-text-muted">
          No providers for this stablecoin
        </div>
      ) : (
        <table className="w-full">
          <thead>
            <tr className="bg-surface-base border-b border-border">
              <th className="text-left px-3 py-2.5 font-mono text-[8.5px] uppercase tracking-wider text-text-muted">
                Protocol
              </th>
              <th className="text-left px-3 py-2.5 font-mono text-[8.5px] uppercase tracking-wider text-text-muted">
                Score adj.
              </th>
              <th className="text-left px-3 py-2.5 font-mono text-[8.5px] uppercase tracking-wider text-text-muted">
                APY
              </th>
              <th className="text-left px-3 py-2.5 font-mono text-[8.5px] uppercase tracking-wider text-text-muted">
                {isCustom ? "Weight %" : "Reference weight"}
              </th>
              <th className="text-left px-3 py-2.5 font-mono text-[8.5px] uppercase tracking-wider text-text-muted">
                Allocated capital
              </th>
            </tr>
          </thead>
          <tbody>
            {providers.map((p, i) => {
              const w = weights[p.name] ?? 0;
              const allocatedCapital = capitalPoche * (w / 100);
              const scoreColor =
                p.adjustedScore >= 70
                  ? "#059669"
                  : p.adjustedScore >= 55
                    ? "#D97706"
                    : p.adjustedScore >= 40
                      ? "#EA580C"
                      : "#DC2626";
              const isTopSelected = !isCustom && i === 0;

              return (
                <tr
                  key={i}
                  className={`border-b border-border last:border-0 transition-colors ${
                    p.suspended ? "opacity-40" : ""
                  } ${isTopSelected ? "ring-1 ring-inset ring-offset-1 " : ""}`}
                  style={
                    isTopSelected
                      ? {
                          backgroundColor:
                            badgeColor === DEFI_COLOR
                              ? "rgba(8, 145, 178, 0.08)"
                              : "rgba(124, 58, 237, 0.08)",
                          boxShadow: "inset 0 0 0 1px " + (badgeColor === DEFI_COLOR ? "rgba(8, 145, 178, 0.25)" : "rgba(124, 58, 237, 0.25)"),
                        }
                      : undefined
                  }
                >
                  <td className="px-3 py-3">
                    <div>
                      <div className="font-medium text-[11.5px] text-text-primary">{p.name}</div>
                      <div className="font-mono text-[8.5px] text-text-muted">{p.protocol}</div>
                    </div>
                  </td>
                  <td className="px-3 py-3">
                    <div className="flex items-center gap-1.5">
                      <span
                        className="font-mono text-[12px] font-semibold"
                        style={{ color: scoreColor }}
                      >
                        {p.adjustedScore}
                      </span>
                      <div className="w-7 h-1 bg-surface-hover rounded-full overflow-hidden">
                        <div
                          className="h-full rounded-full"
                          style={{
                            width: `${p.adjustedScore}%`,
                            background: scoreColor,
                          }}
                        />
                      </div>
                    </div>
                  </td>
                  <td
                    className="whitespace-nowrap px-3 py-3 font-mono text-[11px] font-semibold"
                    style={{ color: p.suspended ? "#9C9488" : "#059669" }}
                  >
                    {p.apy}
                  </td>
                  <td className="px-3 py-3">
                    {isCustom && !p.suspended ? (
                      <div className="flex items-center gap-1.5">
                        <input
                          type="number"
                          min={0}
                          max={100}
                          step={0.5}
                          value={w === 0 ? "" : w}
                          placeholder="0"
                          onChange={(e) =>
                            onWeightChange(p.name, Number(e.target.value) || 0)
                          }
                          className="w-14 bg-surface-base border-[1.5px] border-border rounded-lg px-2 py-1 font-mono text-[11.5px] text-right outline-none font-bold focus:border-border-strong transition-colors"
                          style={
                            sum > 100
                              ? { borderColor: "#DC2626", color: "#DC2626" }
                              : w > 0
                                ? { borderColor: badgeColor + "60", color: badgeColor }
                                : undefined
                          }
                        />
                        <span className="font-mono text-[10px] text-text-muted">%</span>
                        <div className="w-12 h-1.5 bg-surface-hover rounded-full overflow-hidden">
                          <div
                            className="h-full rounded-full transition-all duration-300"
                            style={{
                              width: `${Math.min(w, 100)}%`,
                              background: badgeColor,
                            }}
                          />
                        </div>
                      </div>
                    ) : (
                      <div className="flex items-center gap-1.5">
                        <span
                          className="font-mono text-[11.5px] font-bold"
                          style={{ color: badgeColor }}
                        >
                          {w.toFixed(1)}%
                        </span>
                        <div className="w-12 h-1.5 bg-surface-hover rounded-full overflow-hidden">
                          <div
                            className="h-full rounded-full"
                            style={{
                              width: `${Math.min(w, 100)}%`,
                              background: badgeColor,
                            }}
                          />
                        </div>
                      </div>
                    )}
                  </td>
                  <td className="px-3 py-3 font-mono text-[10.5px] text-text-secondary">
                    {w > 0
                      ? `$${Math.round(allocatedCapital).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                      : "—"}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      )}

      {isCustom && (
        <div
          className="px-4 py-2.5 border-t border-border flex items-center justify-between"
          style={{ background: isValid ? "#05966908" : chipColor + "08" }}
        >
          <span className="font-mono text-[8.5px] text-text-muted uppercase tracking-wider">
            Total allocated in this pocket
          </span>
          <span className="font-mono text-[13px] font-bold" style={{ color: chipColor }}>
            {sum.toFixed(1)}% / 100%
          </span>
        </div>
      )}
    </div>
  );
}

export default function PlannerStablecoinPage() {
  const router = useRouter();
  const {
    state,
    setField,
    selectProto,
    protoOptions,
    projectedIncome,
    multiplier,
    algoCap,
    pegMonitorRows,
    adjustedDefi,
    adjustedCefi,
    capitalDefi,
    capitalCefi,
    weightsDefi,
    weightsCefi,
    sumDefi,
    sumCefi,
    defiValid,
    cefiValid,
    setWeightDefi,
    setWeightCefi,
    activeCefiPct,
    activeDefiPct,
    setCustomDefiPct,
  } = useStablecoinPlanner();
  const { saveSnapshot, setClientInfo, clientInfo } = usePlannerContext();
  const { user } = useSession();
  const [showModal, setShowModal] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  const handleSaveClick = () => {
    setShowModal(true);
  };

  const handleModalConfirm = async (info: ClientInfo) => {
    setGenerating(true);
    setClientInfo(info);
    const snapshot: StablecoinScenarioSnapshot = {
      module: "1C",
      inputs: {
        capital: state.capital ?? 0,
        durationMonths: state.durationMonths ?? 6,
        mode: state.mode,
        selectedProto: state.selectedProto ?? "USDC",
        cefiPct: activeCefiPct,
        defiPct: activeDefiPct,
      },
      results: {
        annualMin: projectedIncome?.annualMin ?? 0,
        annualMax: projectedIncome?.annualMax ?? 0,
        monthlyMin: projectedIncome?.monthlyMin ?? 0,
        monthlyMax: projectedIncome?.monthlyMax ?? 0,
        totalMin: projectedIncome?.totalMin ?? 0,
        totalMax: projectedIncome?.totalMax ?? 0,
      },
      providers: [
        ...adjustedDefi.map((p) => ({
          name: p.name,
          score: p.score,
          adjustedScore: p.adjustedScore,
          apy: p.apy,
          multiplier: p.multiplier,
          category: "DeFi" as const,
          weightPct: weightsDefi[p.name] ?? 0,
        })),
        ...adjustedCefi.filter((p) => !p.suspended).map((p) => ({
          name: p.name,
          score: p.score,
          adjustedScore: p.adjustedScore,
          apy: p.apy,
          multiplier: p.multiplier,
          category: "CeFi" as const,
          weightPct: weightsCefi[p.name] ?? 0,
        })),
      ],
      savedAt: new Date().toISOString(),
    };
    saveSnapshot(snapshot);
    try {
      const res = await fetch("/api/suitability/create-from-planner", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          plannerModule: "1C",
          clientName: info.clientName,
          riskPreference: info.riskPreference,
          snapshot,
        }),
      });
      const data = await res.json().catch(() => ({}));
      if (res.ok && data?.id) {
        setSaveError(null);
        router.push(`/reports?id=${data.id}`);
      } else {
        if (data?.error === "FREE_PLAN_REPORT_LIMIT") {
          setSaveError(data?.message ?? "Free plan allows only one saved report. Delete your existing report or upgrade to PRO.");
        } else {
          console.error("[Stablecoin planner] Save report failed:", res.status, data);
        }
      }
    } catch (e) {
      console.error("[Stablecoin planner] Save report error:", e);
    }
    setGenerating(false);
    setShowModal(false);
  };

  const capital = state.capital ?? 0;

  return (
    <div className="min-h-full w-full max-w-[1600px] space-y-5">
      {saveError && (
        <div
          className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50/90 p-4 font-sans text-sm text-amber-900"
          role="alert"
        >
          <AlertCircle className="h-5 w-5 shrink-0 text-amber-600" aria-hidden />
          <div className="min-w-0 flex-1">
            <p className="font-medium">Cannot save report</p>
            <p className="mt-0.5 text-amber-800">{saveError}</p>
            <div className="mt-3 flex flex-wrap items-center gap-2">
              <Link
                href="/reports"
                className="inline-flex items-center rounded-lg border border-amber-300 bg-white px-3 py-1.5 font-mono text-xs font-medium uppercase tracking-wider text-amber-800 transition-colors hover:bg-amber-50"
              >
                View reports
              </Link>
              <Link
                href="/pricing"
                className="inline-flex items-center rounded-lg border border-amber-400 bg-amber-500 px-3 py-1.5 font-mono text-xs font-medium uppercase tracking-wider text-white transition-colors hover:bg-amber-600"
              >
                Upgrade to PRO
              </Link>
            </div>
          </div>
          <button
            type="button"
            onClick={() => setSaveError(null)}
            className="rounded-lg p-1.5 text-amber-700 transition-colors hover:bg-amber-100"
            aria-label="Dismiss"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      )}
      {/* STAT CARDS */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard
          label="Active stablecoin"
          value={state.selectedProto ?? "—"}
          sub={`${adjustedDefi.length} DeFi · ${adjustedCefi.filter((p) => !p.suspended).length} CeFi`}
          accentColor={STBL}
        />
        <StatCard
          label={`DeFi pocket (${activeDefiPct}%)`}
          value={`$${Math.round(capitalDefi).toLocaleString("en-US", { maximumFractionDigits: 0 })}`}
          sub={`${adjustedDefi.length} provider${adjustedDefi.length !== 1 ? "s" : ""} filtered`}
          accentColor={DEFI_COLOR}
        />
        <StatCard
          label={`CeFi pocket (${activeCefiPct}%)`}
          value={`$${Math.round(capitalCefi).toLocaleString("en-US", { maximumFractionDigits: 0 })}`}
          sub={`${adjustedCefi.filter((p) => !p.suspended).length} active provider${adjustedCefi.filter((p) => !p.suspended).length !== 1 ? "s" : ""}`}
          accentColor={CEFI_COLOR}
        />
        <StatCard
          label="Algo Cap"
          value={`MAX ${algoCap}/100`}
          sub="Algo stablecoin cap"
          accentColor="#DC2626"
        />
      </div>

      {/* GRILLE 2 COLONNES */}
      <div className="grid grid-cols-1 gap-5 lg:grid-cols-[2.1fr_1fr]">
        {/* COLONNE GAUCHE */}
        <div className="space-y-5">
          <div className="bg-white border border-border rounded-xl shadow-sm overflow-hidden">
            <div className="flex items-center justify-between px-5 py-4 border-b border-border">
              <div>
                <div className="font-display font-semibold text-[13px]">
                  ◎ Stablecoin Planner
                </div>
                <div className="font-mono text-[9px] text-text-muted mt-0.5">
                  Allocation {activeCefiPct}% CeFi · {activeDefiPct}% DeFi · Filter by stablecoin
                </div>
              </div>
              <span
                className="font-mono text-[8.5px] px-2 py-0.5 rounded border"
                style={{
                  background: STBL + "15",
                  color: STBL,
                  borderColor: STBL + "40",
                }}
              >
                STABLE
              </span>
            </div>

            <div className="p-5 space-y-5">
              {/* PROTO SELECTOR */}
              <div>
                <div className="font-mono text-[8.5px] uppercase tracking-[2px] font-bold text-text-secondary mb-3 flex items-center gap-2 after:flex-1 after:h-px after:bg-border after:content-['']">
                  Select stablecoin
                </div>
                <div className="flex flex-wrap gap-2">
                  {protoOptions.map((opt) => {
                    const isSelected = state.selectedProto === opt.value;
                    const defiCount =
                      ALL_PROVIDERS_COUNT[opt.value as StablecoinProto]?.defi ?? 0;
                    const cefiCount =
                      ALL_PROVIDERS_COUNT[opt.value as StablecoinProto]?.cefi ?? 0;
                    return (
                      <button
                        key={opt.value}
                        type="button"
                        disabled={opt.disabled}
                        title={opt.tooltip}
                        onClick={() => selectProto(opt.value)}
                        className="flex flex-col items-center rounded-xl border-[1.5px] px-4 py-2.5 font-mono transition-all min-w-[72px]"
                        style={
                          isSelected
                            ? {
                                borderColor: STBL,
                                background: STBL + "12",
                                color: STBL,
                                boxShadow: `0 0 0 2px ${STBL}20`,
                              }
                            : {
                                borderColor: "#E0DBD3",
                                background: "#F5F4F0",
                                color: "#5C564E",
                              }
                        }
                      >
                        <span className="text-[13px] font-bold">{opt.value}</span>
                        <span className="text-[8px] mt-0.5 opacity-70">
                          {defiCount}D · {cefiCount}C
                        </span>
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* INPUTS — Total capital & Duration above Capital allocation */}
              <div className="grid grid-cols-2 gap-3">
                <FormField label="Total capital (USD)">
                  <input
                    type="number"
                    min={0}
                    value={state.capital}
                    onChange={(e) => setField("capital", Number(e.target.value) || 0)}
                    className="w-full bg-surface-base border-[1.5px] border-border rounded-lg px-3 py-2 font-mono text-[12.5px] outline-none focus:border-border-strong transition-colors"
                  />
                </FormField>
                <FormField label="Duration (months)">
                  <select
                    value={state.durationMonths}
                    onChange={(e) => setField("durationMonths", Number(e.target.value))}
                    className="w-full bg-surface-base border-[1.5px] border-border rounded-lg px-3 py-2 font-mono text-[12.5px] outline-none focus:border-border-strong transition-colors"
                  >
                    {[1, 3, 6, 12, 24].map((m) => (
                      <option key={m} value={m}>
                        {m} month{m > 1 ? "s" : ""}
                      </option>
                    ))}
                  </select>
                </FormField>
              </div>

              <FormField label="Income Mode">
                <div
                  className="inline-flex items-center rounded-lg border border-border bg-surface-elevated p-0.5"
                  role="group"
                  aria-label="Income mode"
                >
                  <button
                    type="button"
                    onClick={() => setField("mode", "guided")}
                    title={REFERENCE_SCENARIO_TOOLTIP}
                    aria-label={`Reference Scenario (Illustrative). ${REFERENCE_SCENARIO_TOOLTIP}`}
                    className={`rounded-md px-3 py-1.5 text-sm font-medium transition-colors ${
                      state.mode === "guided"
                        ? "bg-surface-card text-text-primary shadow-sm"
                        : "text-text-secondary hover:text-text-primary"
                    }`}
                  >
                    Reference Scenario (Illustrative)
                  </button>
                  <button
                    type="button"
                    onClick={() => setField("mode", "custom")}
                    title={MY_SCENARIO_TOOLTIP}
                    aria-label={`My Scenario. ${MY_SCENARIO_TOOLTIP}`}
                    className={`rounded-md px-3 py-1.5 text-sm font-medium transition-colors ${
                      state.mode === "custom"
                        ? "bg-surface-card text-text-primary shadow-sm"
                        : "text-text-secondary hover:text-text-primary"
                    }`}
                  >
                    My Scenario
                  </button>
                </div>
              </FormField>

              {/* CAPITAL ALLOCATION */}
              <div>
                <div className="font-mono text-[8.5px] uppercase tracking-[2px] font-bold text-text-secondary mb-3 flex items-center gap-2 after:flex-1 after:h-px after:bg-border after:content-['']">
                  Capital allocation
                </div>
                {state.mode === "guided" ? (
                  <div className="rounded-xl border border-border overflow-hidden">
                    <div className="flex h-8">
                      <div
                        className="flex items-center justify-center font-mono text-[9px] font-bold text-white transition-all"
                        style={{ width: `${activeDefiPct}%`, background: DEFI_COLOR }}
                      >
                        DeFi {activeDefiPct}%
                      </div>
                      <div
                        className="flex items-center justify-center font-mono text-[9px] font-bold text-white transition-all"
                        style={{ width: `${activeCefiPct}%`, background: CEFI_COLOR }}
                      >
                        CeFi {activeCefiPct}%
                      </div>
                    </div>
                    <div className="grid grid-cols-2 divide-x divide-border border-t border-border">
                      <div className="px-4 py-2.5 text-center">
                        <div className="font-mono text-[9px] text-text-muted mb-0.5" style={{ color: DEFI_COLOR }}>
                          DeFi · On-chain
                        </div>
                        <div className="font-display font-bold text-[15px]">
                          ${Math.round(capitalDefi).toLocaleString("en-US", { maximumFractionDigits: 0 })}
                        </div>
                      </div>
                      <div className="px-4 py-2.5 text-center">
                        <div className="font-mono text-[9px] text-text-muted mb-0.5" style={{ color: CEFI_COLOR }}>
                          CeFi · Custodial
                        </div>
                        <div className="font-display font-bold text-[15px]">
                          ${Math.round(capitalCefi).toLocaleString("en-US", { maximumFractionDigits: 0 })}
                        </div>
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="rounded-xl border border-border overflow-hidden">
                    <p className="px-4 py-2 font-mono text-[9px] text-text-muted border-b border-border">
                      Set DeFi % and CeFi %. Total must equal 100%.
                    </p>
                    <div className="grid grid-cols-2 gap-4 p-4">
                      <div>
                        <label className="block font-mono text-[9px] uppercase tracking-wider text-text-muted mb-1.5" style={{ color: DEFI_COLOR }}>
                          DeFi %
                        </label>
                        <input
                          type="number"
                          min={0}
                          max={100}
                          step={1}
                          value={activeDefiPct}
                          onChange={(e) => setCustomDefiPct(Number(e.target.value) || 0)}
                          className="w-full rounded-lg border border-border bg-surface-base px-3 py-2 font-mono text-sm font-bold"
                          style={{ color: DEFI_COLOR }}
                        />
                        <div className="font-display font-bold text-[13px] mt-1">
                          ${Math.round(capitalDefi).toLocaleString("en-US", { maximumFractionDigits: 0 })}
                        </div>
                      </div>
                      <div>
                        <label className="block font-mono text-[9px] uppercase tracking-wider text-text-muted mb-1.5" style={{ color: CEFI_COLOR }}>
                          CeFi %
                        </label>
                        <input
                          type="number"
                          min={0}
                          max={100}
                          step={1}
                          value={activeCefiPct}
                          onChange={(e) => setCustomDefiPct(100 - (Number(e.target.value) || 0))}
                          className="w-full rounded-lg border border-border bg-surface-base px-3 py-2 font-mono text-sm font-bold"
                          style={{ color: CEFI_COLOR }}
                        />
                        <div className="font-display font-bold text-[13px] mt-1">
                          ${Math.round(capitalCefi).toLocaleString("en-US", { maximumFractionDigits: 0 })}
                        </div>
                      </div>
                    </div>
                    <div className="flex h-8 border-t border-border">
                      <div
                        className="flex items-center justify-center font-mono text-[9px] font-bold text-white transition-all"
                        style={{ width: `${activeDefiPct}%`, background: DEFI_COLOR }}
                      >
                        DeFi {activeDefiPct}%
                      </div>
                      <div
                        className="flex items-center justify-center font-mono text-[9px] font-bold text-white transition-all"
                        style={{ width: `${activeCefiPct}%`, background: CEFI_COLOR }}
                      >
                        CeFi {activeCefiPct}%
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* PEG MONITOR */}
              <div>
                <div className="font-mono text-[8.5px] uppercase tracking-[2px] font-bold text-text-secondary mb-3 flex items-center gap-2 after:flex-1 after:h-px after:bg-border after:content-['']">
                  Peg Stability Monitor
                </div>
                <div className="border border-border rounded-xl overflow-hidden bg-surface-base">
                  {pegMonitorRows.map((row, i) => (
                    <div
                      key={row.id}
                      className={`flex items-center gap-3 px-4 py-3 ${
                        i < pegMonitorRows.length - 1 ? "border-b border-border" : ""
                      }`}
                    >
                      <div
                        className="w-8 h-8 rounded-lg flex items-center justify-center font-mono text-[9px] font-bold flex-shrink-0"
                        style={{ background: STBL + "15", color: STBL }}
                      >
                        {row.id.slice(0, 2)}
                      </div>
                      <div className="font-medium text-[12.5px] min-w-[52px]">{row.name}</div>
                      <div className="flex-1 h-1.5 bg-white border border-border rounded-full overflow-hidden">
                        <div
                          className="h-full rounded-full"
                          style={{
                            width: `${row.trackPegPct}%`,
                            background:
                              row.riskBand === "LOW" ? "#059669" : "#D97706",
                          }}
                        />
                      </div>
                      <span
                        className="font-mono text-[10px] font-semibold min-w-[52px] text-right"
                        style={{
                          color: row.riskBand === "LOW" ? "#059669" : "#D97706",
                        }}
                      >
                        +{(row.deviation * 100).toFixed(2)}%
                      </span>
                      <RiskBadge band={row.riskBand} />
                    </div>
                  ))}
                </div>
              </div>

              {/* PROJECTED INCOME — GLOBAL + BY POCKET */}
              <div>
                <div className="font-mono text-[8.5px] uppercase tracking-[2px] font-bold text-text-secondary mb-3 flex items-center gap-2 after:flex-1 after:h-px after:bg-border after:content-['']">
                  Projected Income
                </div>

                <div className="grid grid-cols-2 gap-2 mb-3">
                  <ResultCell
                    label="Annual Min (global)"
                    value={
                      projectedIncome
                        ? `$${Math.round(projectedIncome.annualMin).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                        : "—"
                    }
                    valueColor="#059669"
                    sub="DeFi + CeFi"
                  />
                  <ResultCell
                    label="Annual Max (global)"
                    value={
                      projectedIncome
                        ? `$${Math.round(projectedIncome.annualMax).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                        : "—"
                    }
                    sub="DeFi + CeFi"
                  />
                  <ResultCell
                    label="Monthly Min"
                    value={
                      projectedIncome
                        ? `$${Math.round(projectedIncome.monthlyMin).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                        : "—"
                    }
                  />
                  <ResultCell
                    label="Monthly Max"
                    value={
                      projectedIncome
                        ? `$${Math.round(projectedIncome.monthlyMax).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                        : "—"
                    }
                  />
                  <ResultCell
                    label={`Total ${state.durationMonths}m Min`}
                    value={
                      projectedIncome
                        ? `$${Math.round(projectedIncome.totalMin).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                        : "—"
                    }
                    valueColor="#059669"
                    sub="Prorated duration"
                  />
                  <ResultCell
                    label={`Total ${state.durationMonths}m Max`}
                    value={
                      projectedIncome
                        ? `$${Math.round(projectedIncome.totalMax).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                        : "—"
                    }
                    sub="Prorated duration"
                  />
                </div>

                {projectedIncome && (
                  <div className="grid grid-cols-2 gap-2 pt-3 border-t border-border">
                    <div
                      className="rounded-xl border-[1.5px] p-3"
                      style={{
                        borderColor: DEFI_COLOR + "40",
                        background: DEFI_COLOR + "06",
                      }}
                    >
                      <div
                        className="font-mono text-[8px] uppercase tracking-wider mb-2 font-bold"
                        style={{ color: DEFI_COLOR }}
                      >
                        DeFi {activeDefiPct}% — $
                        {Math.round(capitalDefi).toLocaleString("en-US", {
                          maximumFractionDigits: 0,
                        })}
                      </div>
                      <div className="font-mono text-[9.5px] text-text-secondary space-y-1">
                        <div>
                          APY: {fmtApy(projectedIncome.defi.apyMin)}% – {fmtApy(projectedIncome.defi.apyMax)}%
                        </div>
                        <div>
                          Annual: $
                          {Math.round(projectedIncome.defi.annualMin).toLocaleString("en-US")} – $
                          {Math.round(projectedIncome.defi.annualMax).toLocaleString("en-US")}
                        </div>
                        <div>
                          Monthly: $
                          {Math.round(projectedIncome.defi.monthlyMin).toLocaleString("en-US")} – $
                          {Math.round(projectedIncome.defi.monthlyMax).toLocaleString("en-US")}
                        </div>
                      </div>
                    </div>
                    <div
                      className="rounded-xl border-[1.5px] p-3"
                      style={{
                        borderColor: CEFI_COLOR + "40",
                        background: CEFI_COLOR + "06",
                      }}
                    >
                      <div
                        className="font-mono text-[8px] uppercase tracking-wider mb-2 font-bold"
                        style={{ color: CEFI_COLOR }}
                      >
                        CeFi {activeCefiPct}% — $
                        {Math.round(capitalCefi).toLocaleString("en-US", {
                          maximumFractionDigits: 0,
                        })}
                      </div>
                      <div className="font-mono text-[9.5px] text-text-secondary space-y-1">
                        <div>
                          APY: {fmtApy(projectedIncome.cefi.apyMin)}% – {fmtApy(projectedIncome.cefi.apyMax)}%
                        </div>
                        <div>
                          Annual: $
                          {Math.round(projectedIncome.cefi.annualMin).toLocaleString("en-US")} – $
                          {Math.round(projectedIncome.cefi.annualMax).toLocaleString("en-US")}
                        </div>
                        <div>
                          Monthly: $
                          {Math.round(projectedIncome.cefi.monthlyMin).toLocaleString("en-US")} – $
                          {Math.round(projectedIncome.cefi.monthlyMax).toLocaleString("en-US")}
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* DISCLAIMER */}
              <div
                className="rounded-r-lg border border-border border-l-[3px] bg-surface-base p-4"
                style={{ borderLeftColor: "#DC2626" }}
              >
                <div className="font-mono text-[8.5px] uppercase tracking-wider mb-1.5 font-semibold text-red-600">
                  Hard Rule — Algorithmic Stablecoins
                </div>
                <div className="text-[11.5px] text-text-secondary leading-relaxed">
                  Algorithmic stablecoins (e.g. UST/LUNA-type instruments with no direct collateral backing) are subject to a hard score ceiling of 20/100 under DCC Methodology v1.0. This rule overrides all other criteria while Methodology v1.0 is in force and is subject to formal revision only under the published methodology update process. Any stablecoin with a 90-day maximum peg deviation exceeding 1.5% from USD $1.00 is automatically classified HIGH RISK, overriding all other criteria.
                </div>
              </div>

              <button
                onClick={handleSaveClick}
                disabled={!projectedIncome || generating}
                className="w-full py-2.5 rounded-lg font-mono text-[10px] uppercase
                  tracking-wider text-white font-medium transition-all hover:-translate-y-px
                  disabled:opacity-40 disabled:cursor-not-allowed"
                style={{ background: "#0891B2", boxShadow: "0 2px 8px rgba(8,145,178,0.25)" }}
              >
                Save Scenario & Create Risk Analysis Report →
              </button>
            </div>
          </div>
        </div>

        {/* COLONNE DROITE */}
        <div className="space-y-4">
          <div className="bg-white border border-border rounded-xl shadow-sm overflow-hidden">
            <div className="flex items-center justify-between px-4 py-3.5 border-b border-border">
              <div className="font-display font-semibold text-[13px]">Scoring Criteria</div>
              <span
                className="font-mono text-[8.5px] px-2 py-0.5 rounded border"
                style={{
                  background: STBL + "15",
                  color: STBL,
                  borderColor: STBL + "40",
                }}
              >
                Weights
              </span>
            </div>
            <div className="p-4 space-y-2.5">
              {Object.entries(WEIGHTS.STABLECOIN).map(([key, weight]) => (
                <BreakdownBar
                  key={key}
                  label={CRITERIA_LABELS[key] ?? key}
                  value={(weight as number) * 100}
                  color={STBL}
                  displayValue={`${((weight as number) * 100).toFixed(0)}%`}
                />
              ))}
            </div>
          </div>

          <ProviderTable
            title="Yield Board — DeFi"
            badge="DeFi · On-chain"
            badgeColor={DEFI_COLOR}
            providers={adjustedDefi}
            multiplier={multiplier}
            durationMonths={state.durationMonths ?? 6}
            capitalPoche={capitalDefi}
            weightPct={30}
            mode={state.mode ?? "guided"}
            weights={weightsDefi}
            sum={sumDefi}
            isValid={defiValid}
            onWeightChange={setWeightDefi}
          />

          <ProviderTable
            title="Yield Board — CeFi"
            badge="CeFi · Custodial"
            badgeColor={CEFI_COLOR}
            providers={adjustedCefi}
            multiplier={multiplier}
            durationMonths={state.durationMonths ?? 6}
            capitalPoche={capitalCefi}
            weightPct={70}
            mode={state.mode ?? "guided"}
            weights={weightsCefi}
            sum={sumCefi}
            isValid={cefiValid}
            onWeightChange={setWeightCefi}
          />
        </div>
      </div>

      {showModal && (
        <ClientInfoModal
          module="1C"
          defaultClientName={clientInfo?.clientName ?? user?.name ?? ""}
          onConfirm={handleModalConfirm}
          onCancel={() => { if (!generating) setShowModal(false); }}
          generating={generating}
        />
      )}
    </div>
  );
}
