"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useFiatPlanner } from "@/hooks/useFiatPlanner";
import { ClientInfoModal } from "@/components/planner/ClientInfoModal";
import { usePlannerContext } from "@/context/PlannerContext";
import type { ClientInfo, FiatScenarioSnapshot } from "@/context/PlannerContext";
import { generateAndDownloadFiatPdf } from "@/lib/pdf/generateFiatPdf";
import { useSession, canExportPdf } from "@/hooks/useSession";
import { StatCard } from "@/components/ui/StatCard";
import { FormField } from "@/components/ui/FormField";
import { InstrumentCard } from "@/components/planner/InstrumentCard";
import { ResultCell } from "@/components/ui/ResultCell";
import { BreakdownBar } from "@/components/ui/BreakdownBar";
import { Button } from "@/components/ui/Button";
import { WEIGHTS } from "@/lib/scoring/weights";
import { getDurationMultiplier } from "@/lib/scoring/engine";

const REFERENCE_SCENARIO_TOOLTIP =
  "This is an illustrative benchmark generated by the DCC scoring engine. It is not a personalised recommendation. Define your own scenario in the My Scenario tab before acting.";

const MY_SCENARIO_TOOLTIP =
  "You are building this scenario. All allocation weights, provider selections, and inputs are your own choices. DCC provides scoring data only.";

const DURATION_OPTIONS = [1, 3, 6, 12, 24, 36] as const;

export default function PlannerFiatPage() {
  const router = useRouter();
  const {
    state,
    setField,
    toggleInstrument,
    setCustomWeight,
    instruments,
    selectedInstruments,
    adjustedScores,
    blendedApy,
    projectedIncome,
    hv30Warning,
    weightsTotal,
    effectiveWeights,
  } = useFiatPlanner();
  const { saveSnapshot, setClientInfo, clientInfo } = usePlannerContext();
  const { user } = useSession();
  const allowPdf = canExportPdf(user?.role);
  const [showModal, setShowModal] = useState(false);
  const [generating, setGenerating] = useState(false);

  const handleSaveClick = () => {
    setShowModal(true);
  };

  const handleModalConfirm = async (info: ClientInfo) => {
    setGenerating(true);
    setClientInfo(info);
    const snapshot: FiatScenarioSnapshot = {
      module: "1B",
      inputs: {
        capital: state.capital,
        durationMonths: state.durationMonths ?? 0,
        mode: state.mode,
        selectedTickers:
          state.mode === "guided"
            ? selectedInstruments.map((i) => i.ticker)
            : state.selectedTickers,
      },
      results: {
        annualMin: projectedIncome?.annualMin ?? 0,
        annualMax: projectedIncome?.annualMax ?? 0,
        monthlyMin: projectedIncome?.monthlyMin ?? 0,
        monthlyMax: projectedIncome?.monthlyMax ?? 0,
        totalMin: projectedIncome?.totalMin ?? 0,
        totalMax: projectedIncome?.totalMax ?? 0,
      },
      instruments: adjustedScores.map((s) => ({
        ticker: s.ticker,
        name: s.name,
        dccScore: s.dccScore,
        adjustedScore: s.adjustedScore,
        multiplier: s.multiplier,
        apyEstimate: s.apyEstimate,
        hv30: s.hv30,
        riskBand: s.riskBand,
      })),
      blendedApy: {
        min: blendedApy.min,
        max: blendedApy.max,
      },
      allocationWeights: state.mode === "guided" ? Object.fromEntries(selectedInstruments.map((i) => [i.ticker, effectiveWeights[i.ticker] ?? 0])) : state.customWeights,
      savedAt: new Date().toISOString(),
    };
    saveSnapshot(snapshot);
    try {
      const res = await fetch("/api/suitability/create-from-planner", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          plannerModule: "1B",
          clientName: info.clientName,
          riskPreference: info.riskPreference,
          snapshot,
        }),
      });
      const data = await res.json().catch(() => ({}));
      if (res.ok && data?.id) {
        if (allowPdf) await generateAndDownloadFiatPdf(snapshot, info);
        router.push(`/reports?id=${data.id}`);
      } else {
        console.error("[Fiat planner] Save report failed:", res.status, data);
        if (allowPdf) await generateAndDownloadFiatPdf(snapshot, info);
      }
    } catch (e) {
      console.error("[Fiat planner] Save report error:", e);
      if (allowPdf) await generateAndDownloadFiatPdf(snapshot, info);
    }
    setGenerating(false);
    setShowModal(false);
  };

  const fiatWeights = WEIGHTS.FIAT as Record<string, number>;
  const criteriaLabels: Record<string, string> = {
    marketVolatility: "Market Volatility",
    incomeMechanism: "Income Mechanism",
    seniority: "Seniority",
    complexity: "Complexity",
    providerQuality: "Provider Quality",
  };

  return (
    <div className="min-h-full w-full max-w-[1600px] space-y-6">
      {/* 1. STAT CARDS ROW */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
        <StatCard
          label="Selected Instruments"
          value={selectedInstruments.length}
          sub={
            selectedInstruments.length > 0
              ? selectedInstruments.map((i) => i.ticker).join(", ")
              : undefined
          }
          accentColor="#4F46E5"
        />
        <StatCard
          label="Blended APY Range"
          value={
            selectedInstruments.length > 0
              ? blendedApy.min === blendedApy.max
                ? `${blendedApy.min.toFixed(1)}%`
                : `${blendedApy.min.toFixed(1)}% – ${blendedApy.max.toFixed(1)}%`
              : "—"
          }
          accentColor="var(--color-risk-low)"
        />
        <StatCard
          label="HV30 Hard Cap Rule"
          value={hv30Warning ? "⚠ Warning" : "OK"}
          sub={
            hv30Warning
              ? "One or more instruments exceed 35% HV30 (C1 capped)"
              : undefined
          }
          accentColor={hv30Warning ? "var(--color-risk-mid)" : "var(--color-risk-low)"}
        />
      </div>

      {/* 2. GRILLE 2 COLONNES */}
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-[2.1fr_1fr]">
        {/* COLONNE GAUCHE */}
        <div className="space-y-6">
          <section className="rounded-lg border border-border bg-surface-card p-5">
            <h2 className="mb-4 font-heading text-sm font-semibold uppercase tracking-wider text-text-primary">
              Inputs
            </h2>
            <div className="grid gap-4 sm:grid-cols-2">
              <FormField label="Capital (USD)" required>
                <input
                  type="number"
                  min={0}
                  value={state.capital ?? ""}
                  onChange={(e) =>
                    setField(
                      "capital",
                      e.target.value ? Number(e.target.value) : 0
                    )
                  }
                  className="w-full rounded border border-border bg-surface-base px-3 py-2 font-mono text-sm"
                />
              </FormField>
              <FormField label="Duration">
                <select
                  value={state.durationMonths ?? 12}
                  onChange={(e) =>
                    setField("durationMonths", Number(e.target.value))
                  }
                  className="w-full rounded border border-border bg-surface-base px-3 py-2 font-mono text-sm"
                >
                  {DURATION_OPTIONS.map((m) => (
                    <option key={m} value={m}>
                      {m} month{m !== 1 ? "s" : ""}
                    </option>
                  ))}
                </select>
              </FormField>
            </div>
            <div className="mt-4">
              <h2 className="mb-3 font-heading text-sm font-semibold uppercase tracking-wider text-text-primary">
                Allocation
              </h2>
              <div
                className="inline-flex items-center rounded-lg border border-border bg-surface-elevated p-0.5"
                role="group"
                aria-label="Allocation mode"
              >
                <button
                  type="button"
                  onClick={() => setField("mode", "guided")}
                  title={REFERENCE_SCENARIO_TOOLTIP}
                  aria-label={`Reference Scenario (Illustrative). ${REFERENCE_SCENARIO_TOOLTIP}`}
                  className={`rounded-md px-3 py-1.5 text-sm font-medium transition-colors ${
                    state.mode === "guided"
                      ? "bg-surface-card text-text-primary shadow-sm"
                      : "text-text-secondary hover:text-text-primary"
                  }`}
                >
                  Reference Scenario (Illustrative)
                </button>
                <button
                  type="button"
                  onClick={() => setField("mode", "custom")}
                  title={MY_SCENARIO_TOOLTIP}
                  aria-label={`My Scenario. ${MY_SCENARIO_TOOLTIP}`}
                  className={`rounded-md px-3 py-1.5 text-sm font-medium transition-colors ${
                    state.mode === "custom"
                      ? "bg-surface-card text-text-primary shadow-sm"
                      : "text-text-secondary hover:text-text-primary"
                  }`}
                >
                  My Scenario
                </button>
              </div>
            </div>
          </section>

          {state.mode === "guided" && selectedInstruments.length > 0 && (
            <section className="rounded-lg border border-border bg-surface-card p-5">
              <h2 className="mb-2 font-heading text-sm font-semibold uppercase tracking-wider text-text-primary">
                Reference Scenario (Illustrative)
              </h2>
              <p className="mb-3 font-mono text-xs text-text-muted">
                Top 3 providers by duration-adjusted score: 60% / 20% / 20%.
              </p>
              <div className="space-y-2">
                {selectedInstruments.map((inst) => (
                  <div
                    key={inst.ticker}
                    className="flex flex-wrap items-center gap-3 rounded-lg border border-border bg-surface-elevated p-3"
                  >
                    <div className="min-w-0 flex-1">
                      <p className="font-medium text-text-primary">{inst.ticker}</p>
                      <p className="truncate font-mono text-xs text-text-muted">{inst.name}</p>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-sm font-semibold text-text-primary">
                        {effectiveWeights[inst.ticker]?.toFixed(1) ?? "—"}%
                      </span>
                      <div className="h-2 w-16 shrink-0 overflow-hidden rounded-full bg-surface-hover">
                        <div
                          className="h-full rounded-full bg-[#4F46E5]"
                          style={{ width: `${effectiveWeights[inst.ticker] ?? 0}%` }}
                        />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}

          {state.mode === "custom" && (
            <section className="rounded-lg border border-border bg-surface-card p-5">
              <h2 className="mb-2 font-heading text-sm font-semibold uppercase tracking-wider text-text-primary">
                Select Instruments
              </h2>
              <p className="mb-3 font-mono text-xs text-text-muted">
                Choose the instruments you want to include in your allocation.
              </p>
              <div className="space-y-2">
                {instruments.map((inst) => (
                  <InstrumentCard
                    key={inst.ticker}
                    ticker={inst.ticker}
                    name={inst.name}
                    dccScore={inst.dccScore}
                    apyEstimate={inst.apyEstimate}
                    hv30={inst.hv30}
                    riskBand={inst.riskBand}
                    selected={state.selectedTickers.includes(inst.ticker)}
                    onToggle={() => toggleInstrument(inst.ticker)}
                    disabled={inst.disabled}
                  />
                ))}
              </div>
            </section>
          )}

          {state.mode === "custom" && selectedInstruments.length > 0 && (
            <section className="rounded-lg border border-border bg-surface-card p-5">
              <h2 className="mb-2 font-heading text-sm font-semibold uppercase tracking-wider text-text-primary">
                My Scenario allocation
              </h2>
              <p className="mb-3 font-mono text-xs text-text-muted">
                Assign a percentage of capital to each selected instrument. Total must equal 100%.
              </p>
              <div className="space-y-3">
                {selectedInstruments.map((inst) => {
                  const defaultPct =
                    selectedInstruments.length
                      ? parseFloat((100 / selectedInstruments.length).toFixed(2))
                      : 0;
                  const pct = Math.min(
                    100,
                    Math.max(0, state.customWeights[inst.ticker] ?? defaultPct)
                  );
                  return (
                    <div
                      key={inst.ticker}
                      className="flex flex-wrap items-center gap-3 rounded-lg border border-border bg-surface-elevated p-3"
                    >
                      <div className="min-w-0 flex-1">
                        <p className="font-medium text-text-primary">{inst.ticker}</p>
                        <p className="truncate font-mono text-xs text-text-muted">{inst.name}</p>
                      </div>
                      <div className="flex items-center gap-2">
                        <input
                          type="number"
                          min={0}
                          max={100}
                          step={1}
                          value={pct}
                          onChange={(e) =>
                            setCustomWeight(
                              inst.ticker,
                              e.target.value === "" ? 0 : Number(e.target.value)
                            )
                          }
                          className="w-14 rounded border border-border bg-surface-card px-2 py-1.5 text-right font-mono text-sm"
                        />
                        <span className="font-mono text-xs text-text-muted">%</span>
                      </div>
                      <div className="h-2 w-16 shrink-0 overflow-hidden rounded-full bg-surface-hover">
                        <div
                          className="h-full rounded-full bg-[#4F46E5]"
                          style={{ width: `${pct}%` }}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
              <div className="mt-3 flex items-center justify-between border-t border-border pt-3">
                <span className="font-mono text-xs text-text-muted">Total</span>
                <span
                  className="font-mono text-sm font-semibold"
                  style={{
                    color:
                      Math.abs(weightsTotal - 100) < 0.5
                        ? "var(--color-risk-low)"
                        : weightsTotal < 100
                          ? "var(--color-risk-mid)"
                          : "var(--color-risk-high)",
                  }}
                >
                  {weightsTotal.toFixed(1)}%
                </span>
              </div>
              {Math.abs(weightsTotal - 100) >= 0.5 && (
                <p className="mt-2 font-mono text-xs font-medium text-text-muted">
                  Total must equal 100% to save the scenario.
                </p>
              )}
            </section>
          )}

          <section className="rounded-lg border border-border bg-surface-card p-5">
            <h2 className="mb-4 font-heading text-sm font-semibold uppercase tracking-wider text-text-primary">
              Projected Income
            </h2>
            <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
              <ResultCell
                label="Annual Income Min"
                value={
                  projectedIncome != null
                    ? `$${Math.round(projectedIncome.annualMin).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                    : "—"
                }
                sub={`at blended ${blendedApy.min.toFixed(1)}%`}
                valueColor="#059669"
              />
              <ResultCell
                label="Annual Income Max"
                value={
                  projectedIncome != null
                    ? `$${Math.round(projectedIncome.annualMax).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                    : "—"
                }
                sub={`at blended ${blendedApy.max.toFixed(1)}%`}
              />
              <ResultCell
                label="Monthly Min"
                value={
                  projectedIncome != null
                    ? `$${Math.round(projectedIncome.monthlyMin).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                    : "—"
                }
              />
              <ResultCell
                label="Monthly Max"
                value={
                  projectedIncome != null
                    ? `$${Math.round(projectedIncome.monthlyMax).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                    : "—"
                }
              />
              <ResultCell
                label={`Total over ${state.durationMonths} months (min)`}
                value={
                  projectedIncome != null
                    ? `$${Math.round(projectedIncome.totalMin).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                    : "—"
                }
                sub="Prorated over duration"
                valueColor="#059669"
              />
              <ResultCell
                label={`Total over ${state.durationMonths} months (max)`}
                value={
                  projectedIncome != null
                    ? `$${Math.round(projectedIncome.totalMax).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
                    : "—"
                }
                sub="Prorated over duration"
              />
            </div>
          </section>

          <div className="rounded-xl border border-border bg-white shadow-sm overflow-hidden">
            <div className="flex items-center justify-between border-b border-border px-5 py-3.5">
              <div className="font-display font-semibold text-[13px] text-text-primary">
                Adjusted DCC score
              </div>
              <span
                className="rounded border px-2 py-0.5 font-mono text-[8.5px]"
                style={{
                  background: "rgba(79,70,229,0.08)",
                  color: "#4F46E5",
                  borderColor: "rgba(79,70,229,0.2)",
                }}
              >
                ×{adjustedScores[0]?.multiplier.toFixed(2) ?? "—"} duration mult.
              </span>
            </div>
            <div className="p-4">
              {adjustedScores.length === 0 ? (
                <p className="py-2 text-center font-sans text-[11.5px] text-text-muted">
                  Select at least one instrument
                </p>
              ) : (
                <div className="space-y-2.5">
                  {adjustedScores.map((s) => (
                    <div key={s.ticker} className="flex items-center gap-3">
                      <span
                        className="min-w-[44px] font-mono text-[11px] font-bold"
                        style={{ color: "#4F46E5" }}
                      >
                        {s.ticker}
                      </span>
                      <div className="h-1 flex-1 overflow-hidden rounded-full bg-surface-hover">
                        <div
                          className="h-full rounded-full transition-all duration-500"
                          style={{
                            width: `${s.adjustedScore}%`,
                            background:
                              s.adjustedScore >= 60 ? "#D97706" : "#EA580C",
                          }}
                        />
                      </div>
                      <div className="flex min-w-[90px] items-center justify-end gap-1.5">
                        <span className="font-mono text-[10px] text-text-muted line-through">
                          {s.dccScore}
                        </span>
                        <span className="font-mono text-[11px] font-semibold text-text-primary">
                          → {s.adjustedScore}
                        </span>
                      </div>
                    </div>
                  ))}
                  <p className="mt-2 border-t border-border pt-2 font-mono text-[8.5px] text-text-muted">
                    Raw score × duration multiplier — append-only, never recalculated
                  </p>
                </div>
              )}
            </div>
          </div>

          <div
            className="rounded-r border border-border border-l-4 bg-surface-elevated p-4"
            style={{ borderLeftColor: "#D97706" }}
          >
            <p className="font-mono text-xs font-medium uppercase tracking-wider text-text-primary">
              HV30 Hard Cap
            </p>
            <p className="mt-1 text-sm text-text-secondary">
              Instruments with HV30 &gt; 35% have C1 (market volatility) capped at 5/30 in the scoring engine. Consider reducing allocation to high-HV30 instruments.
            </p>
          </div>

          <button
            onClick={handleSaveClick}
            disabled={
              selectedInstruments.length === 0 ||
              (state.capital ?? 0) <= 0 ||
              (state.mode === "custom" && Math.abs(weightsTotal - 100) >= 0.5)
            }
            className="w-full py-2.5 rounded-lg font-mono text-[10px] uppercase
              tracking-wider text-white font-medium transition-all hover:-translate-y-px
              disabled:opacity-40 disabled:cursor-not-allowed"
            style={{ background: "#4F46E5", boxShadow: "0 2px 8px rgba(79,70,229,0.25)" }}
          >
            Save Scenario & Create Risk Analysis Report →
          </button>
        </div>

        {/* COLONNE DROITE */}
        <div className="space-y-6">
          <div className="overflow-hidden rounded-xl border border-border bg-white shadow-sm">
            <div className="flex items-center justify-between border-b border-border px-4 py-3.5">
              <div className="font-display font-semibold text-[13px] text-text-primary">
                Scoring Criteria
              </div>
              <span
                className="rounded border px-2 py-0.5 font-mono text-[8.5px]"
                style={{
                  background: "rgba(79,70,229,0.08)",
                  color: "#4F46E5",
                  borderColor: "rgba(79,70,229,0.2)",
                }}
              >
                Weights
              </span>
            </div>
            <div className="space-y-2.5 p-4">
              {Object.entries(fiatWeights).map(([key, weight]) => (
                <BreakdownBar
                  key={key}
                  label={criteriaLabels[key] ?? key}
                  value={weight * 100}
                  color="#4F46E5"
                  displayValue={`${(weight * 100).toFixed(0)}%`}
                />
              ))}
            </div>
          </div>

          <div className="overflow-hidden rounded-xl border border-border bg-white shadow-sm">
            <div className="flex items-center justify-between border-b border-border px-4 py-3.5">
              <div>
                <div className="font-display font-semibold text-[13px] text-text-primary">
                  Yield Board
                </div>
                <div className="mt-0.5 font-mono text-[9px] text-text-muted">
                  Duration-adjusted score {state.durationMonths}m · ×
                  {adjustedScores[0]?.multiplier.toFixed(2) ?? "1.00"}
                </div>
              </div>
              <span
                className="rounded border px-2 py-0.5 font-mono text-[8.5px]"
                style={{
                  background: "rgba(79,70,229,0.08)",
                  color: "#4F46E5",
                  borderColor: "rgba(79,70,229,0.2)",
                }}
              >
                BTC Prefs
              </span>
            </div>
            <table className="w-full">
              <thead>
                <tr className="border-b border-border bg-surface-base">
                  {["Ticker", "Raw", "Adjusted", "APY", "HV30"].map((h) => (
                    <th
                      key={h}
                      className="px-3 py-2.5 text-left font-mono text-[8.5px] uppercase tracking-wider text-text-muted"
                    >
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {instruments.map((inst) => {
                  const adjusted = adjustedScores.find(
                    (a) => a.ticker === inst.ticker
                  );
                  const mult =
                    adjusted?.multiplier ??
                    getDurationMultiplier(state.durationMonths);
                  const adjustedScore = parseFloat(
                    (inst.dccScore * mult).toFixed(1)
                  );
                  const isSelected = selectedInstruments.some(
                    (s) => s.ticker === inst.ticker
                  );
                  const isGuided = state.mode === "guided";

                  return (
                    <tr
                      key={inst.ticker}
                      className={`border-b border-border last:border-0 transition-colors ${
                        isSelected ? "bg-indigo-50/40" : ""
                      } ${
                        inst.hv30 > 35
                          ? "opacity-60"
                          : isGuided
                            ? ""
                            : "cursor-pointer hover:bg-surface-elevated"
                      }`}
                      onClick={() => !isGuided && toggleInstrument(inst.ticker)}
                    >
                      <td className="px-3 py-3">
                        <div className="flex items-center gap-1.5">
                          {isSelected && (
                            <span
                              className="h-1.5 w-1.5 flex-shrink-0 rounded-full"
                              style={{ background: "#4F46E5" }}
                            />
                          )}
                          <span
                            className="font-mono text-[12px] font-bold"
                            style={{ color: "#4F46E5" }}
                          >
                            {inst.ticker}
                          </span>
                        </div>
                      </td>
                      <td className="px-3 py-3 font-mono text-[11px] text-text-muted line-through">
                        {inst.dccScore}
                      </td>
                      <td className="px-3 py-3">
                        <div className="flex items-center gap-1.5">
                          <span
                            className="font-mono text-[12px] font-semibold"
                            style={{
                              color:
                                adjustedScore >= 60 ? "#D97706" : "#EA580C",
                            }}
                          >
                            {adjustedScore}
                          </span>
                          <div className="h-1 w-10 overflow-hidden rounded-full bg-surface-hover">
                            <div
                              className="h-full rounded-full"
                              style={{
                                width: `${adjustedScore}%`,
                                background:
                                  adjustedScore >= 60 ? "#D97706" : "#EA580C",
                              }}
                            />
                          </div>
                        </div>
                      </td>
                      <td className="whitespace-nowrap px-3 py-3 font-mono text-[11px] font-semibold text-risk-low">
                        ~{inst.apyEstimate}%
                      </td>
                      <td
                        className="px-3 py-3 font-mono text-[11px]"
                        style={{
                          color:
                            inst.hv30 > 35
                              ? "#DC2626"
                              : "var(--color-text-secondary)",
                        }}
                      >
                        {inst.hv30}%{inst.hv30 > 35 ? " ⚠" : ""}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
            <div className="flex items-center gap-3 border-t border-border bg-surface-base px-4 py-2.5">
              <span className="font-mono text-[8px] uppercase tracking-wider text-text-muted">
                Legend
              </span>
              <span className="font-mono text-[8.5px] text-text-muted line-through">
                Raw score
              </span>
              <span
                className="font-mono text-[8.5px]"
                style={{ color: "#D97706" }}
              >
                Score × duration mult.
              </span>
              <span className="ml-auto flex items-center gap-1 font-mono text-[8.5px] text-text-muted">
                <span
                  className="h-1.5 w-1.5 rounded-full"
                  style={{ background: "#4F46E5" }}
                />
                Selected
              </span>
            </div>
          </div>
        </div>
      </div>

      {showModal && (
        <ClientInfoModal
          module="1B"
          defaultClientName={clientInfo?.clientName ?? user?.name ?? ""}
          onConfirm={handleModalConfirm}
          onCancel={() => { if (!generating) setShowModal(false); }}
          generating={generating}
        />
      )}
    </div>
  );
}
