import type { Metadata } from "next";
import Link from "next/link";
import { LandingHeader } from "@/components/landing/LandingHeader";
import { LandingFooter } from "@/components/landing/LandingFooter";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "Terms and Conditions governing access to and use of the Digital Credit Compass (DCC) platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-surface-base">
      <LandingHeader />
      <main className="mx-auto max-w-4xl px-4 py-12 sm:px-6 sm:py-16">
        <div className="rounded-xl border border-border bg-surface-card p-6 shadow-sm sm:p-8 lg:p-10">
          <header className="border-b border-border pb-6">
            <p className="text-sm font-medium text-text-muted">v2.0 · March 2026</p>
            <h1 className="font-heading mt-1 text-3xl font-bold text-text-primary sm:text-4xl">
              Terms and Conditions
            </h1>
            <p className="mt-2 text-lg text-text-secondary">
              Governing Access to and Use of the Digital Credit Compass (DCC) Platform
            </p>
          </header>

          <div className="prose prose-sm mt-8 max-w-none prose-headings:font-heading prose-headings:font-semibold prose-headings:text-text-primary prose-p:text-text-secondary prose-li:text-text-secondary prose-strong:text-text-primary">
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">1. Defined Terms and Interpretation</h2>
              <p className="mt-2 text-sm text-text-secondary">
                The following definitions apply throughout these Terms and Conditions.
              </p>
              <div className="mt-4 overflow-x-auto">
                <table className="min-w-full border-collapse border border-border text-sm">
                  <thead>
                    <tr className="bg-surface-elevated">
                      <th className="border border-border px-4 py-2 text-left font-semibold text-text-primary">Term</th>
                      <th className="border border-border px-4 py-2 text-left font-semibold text-text-primary">Definition</th>
                    </tr>
                  </thead>
                  <tbody className="text-text-secondary">
                    <tr><td className="border border-border px-4 py-2">&quot;Company&quot; / &quot;DCC&quot; / &quot;We&quot;</td><td className="border border-border px-4 py-2">Digital Credit Compass, operator of the Platform, including its affiliates, successors, and permitted assigns.</td></tr>
                    <tr><td className="border border-border px-4 py-2">&quot;Platform&quot;</td><td className="border border-border px-4 py-2">The Digital Credit Compass SaaS application, including all planners, scoring engines, dashboards, APIs, documentation, and associated digital infrastructure.</td></tr>
                    <tr><td className="border border-border px-4 py-2">&quot;User&quot; / &quot;You&quot;</td><td className="border border-border px-4 py-2">Any individual or entity accessing, registering for, or using any part of the Platform — including free-tier, paid subscriber, enterprise, and API users.</td></tr>
                    <tr><td className="border border-border px-4 py-2">&quot;Subscriber&quot;</td><td className="border border-border px-4 py-2">A User who has entered into a paid subscription agreement for access to Platform features beyond any free tier.</td></tr>
                    <tr><td className="border border-border px-4 py-2">&quot;Enterprise Client&quot;</td><td className="border border-border px-4 py-2">A User who has executed a separate Enterprise Services Agreement governing commercial-scale access, API rights, white-labelling, or institutional data feeds.</td></tr>
                    <tr><td className="border border-border px-4 py-2">&quot;Services&quot;</td><td className="border border-border px-4 py-2">All analytical, scoring, scenario modelling, and data presentation functions made available through the Platform.</td></tr>
                    <tr><td className="border border-border px-4 py-2">&quot;DCC Score&quot;</td><td className="border border-border px-4 py-2">Any risk score, composite metric, rating band, Scenario Risk Index value, or analytical output generated by the DCC scoring engine.</td></tr>
                    <tr><td className="border border-border px-4 py-2">&quot;Applicable Law&quot;</td><td className="border border-border px-4 py-2">All laws, regulations, rules, and guidance applicable to a User&apos;s access and use of the Platform in their jurisdiction of access or residence.</td></tr>
                    <tr><td className="border border-border px-4 py-2">&quot;Force Majeure Event&quot;</td><td className="border border-border px-4 py-2">Any event beyond a party&apos;s reasonable control, including cyberattacks, API failures, regulatory action, or infrastructure outage.</td></tr>
                    <tr><td className="border border-border px-4 py-2">&quot;Intellectual Property&quot;</td><td className="border border-border px-4 py-2">All patents, trade secrets, copyrights, trademarks, database rights, algorithms, source code, and know-how owned or licensed by the Company.</td></tr>
                  </tbody>
                </table>
              </div>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">2. Overview and Acceptance</h2>
              <p className="mt-2 text-text-secondary">
                These Terms and Conditions (&quot;Terms&quot;), together with the Privacy Policy, Disclaimer, Acceptable Use Policy, Cookie Policy, and any separately executed Enterprise Services Agreement or Data Processing Addendum, constitute the entire legal agreement between the User and the Company (the &quot;Framework&quot;).
              </p>
              <p className="mt-3 text-text-secondary">
                By accessing the Platform in any manner — including browsing the website, registering an account, activating a subscription, consuming the API, or accessing any output — the User unconditionally accepts and agrees to be bound by the Framework in its then-current version.
              </p>
              <p className="mt-3 text-text-secondary">
                If a User does not accept these Terms in their entirety, they must immediately cease all access to and use of the Platform. Continued use following publication of amended Terms constitutes acceptance of the amended version.
              </p>
              <div className="mt-4 rounded-lg border border-risk-mid bg-risk-mid-bg px-4 py-3 text-sm text-text-primary">
                <strong>IMPORTANT NOTICE — READ BEFORE PROCEEDING</strong>
                <p className="mt-2 text-text-secondary">
                  These Terms and Conditions constitute a binding legal agreement between you and Digital Credit Compass. By accessing or using the Platform in any manner, you unconditionally accept these Terms in their entirety. If you do not accept these Terms, you must immediately cease all access and use of the Platform. Digital Credit Compass is an analytics platform only. Nothing in these Terms creates an advisory relationship.
                </p>
              </div>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">3. Nature and Scope of Services</h2>
              <p className="mt-2 text-text-secondary">
                The Platform provides the following categories of service:
              </p>
              <ul className="mt-3 list-disc space-y-2 pl-6 text-text-secondary">
                <li><strong className="text-text-primary">Risk Scoring Engine:</strong> Deterministic, rule-based analytical scores for digital asset income products across three planner modules — Planner 1A (BTC-collateralised lending), Planner 1B (BTC treasury preferred shares), and Planner 1C (stablecoin yield products).</li>
                <li><strong className="text-text-primary">Scenario Modelling:</strong> Parametric income scenario outputs generated from user-supplied inputs and DCC scoring data, presented as illustrative benchmarks only.</li>
                <li><strong className="text-text-primary">Yield Intelligence Dashboard:</strong> Structured presentation of scored products, risk band classifications, duration-adjusted metrics, and comparative analytics.</li>
                <li><strong className="text-text-primary">Data Feeds and API:</strong> Machine-readable access to DCC scores and related data, subject to separate API Terms of Service.</li>
                <li><strong className="text-text-primary">Methodology Documentation:</strong> Published documentation of all scoring criteria, weights, sub-criteria, and data sources underpinning every DCC Score.</li>
              </ul>
              <p className="mt-4 text-text-secondary">
                The Platform does <strong>NOT</strong> execute transactions, provide custody, act as a financial intermediary, issue financial instruments, or provide regulated financial services of any kind.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">4. No Advisory Relationship</h2>
              <p className="mt-2 text-text-secondary">
                No communication, output, score, report, document, API response, or interface element produced by the Platform constitutes investment advice, financial advice, a credit rating, a suitability or appropriateness assessment, or any other form of regulated financial service.
              </p>
              <p className="mt-3 text-text-secondary">
                No fiduciary duty, advisory duty, or duty of care is created between the Company and any User by virtue of access to or use of the Platform, regardless of the frequency of use, the nature of outputs consumed, or any communications exchanged.
              </p>
              <p className="mt-3 text-text-secondary">
                Users who rely on DCC outputs in connection with investment decisions do so entirely at their own risk. The Company strongly recommends that all Users obtain independent, qualified professional advice — including legal, financial, tax, and compliance advice — before making any investment or capital allocation decision.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">5. User Eligibility and Ongoing Obligations</h2>
              <p className="mt-2 text-text-secondary">
                To access the Platform, Users must be at least 18 years of age, have legal capacity to enter into binding contracts, not be prohibited from receiving digital asset-related analytical services under Applicable Law, and not be accessing from a jurisdiction where the Company&apos;s services are restricted or would require regulatory authorisation that the Company does not hold.
              </p>
              <p className="mt-3 text-text-secondary">
                Users represent and warrant on an ongoing basis that all information provided is accurate and complete; use of the Platform is solely for lawful purposes; they are solely responsible for all decisions made in reliance on Platform outputs; and they have obtained all necessary independent professional advice before acting on any output.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">6. Risk Acknowledgment</h2>
              <p className="mt-2 text-text-secondary">
                Users expressly acknowledge and accept the following material risk factors:
              </p>
              <div className="mt-4 rounded-lg border border-border bg-surface-elevated px-4 py-3 text-sm">
                <strong className="text-text-primary">IMPORTANT DISTINCTION</strong>
                <p className="mt-2 text-text-secondary">
                  DCC is a data analytics and intelligence platform. It is structurally and legally distinct from investment advisers, credit rating agencies, robo-advisers, and regulated financial intermediaries. DCC&apos;s outputs are analytical information, not regulated advice.
                </p>
              </div>
              <div className="mt-4 overflow-x-auto">
                <table className="min-w-full border-collapse border border-border text-sm">
                  <thead>
                    <tr className="bg-surface-elevated">
                      <th className="border border-border px-4 py-2 text-left font-semibold text-text-primary">Risk Category</th>
                      <th className="border border-border px-4 py-2 text-left font-semibold text-text-primary">Description</th>
                      <th className="border border-border px-4 py-2 text-left font-semibold text-text-primary">DCC Scoring Treatment</th>
                    </tr>
                  </thead>
                  <tbody className="text-text-secondary">
                    <tr>
                      <td className="border border-border px-4 py-2">Price Volatility</td>
                      <td className="border border-border px-4 py-2">BTC-linked instruments are subject to extreme price movements. Historical data reflects past performance only.</td>
                      <td className="border border-border px-4 py-2">Automated daily HV30 scoring with hard cap rules. Scores change materially day-to-day.</td>
                    </tr>
                    <tr>
                      <td className="border border-border px-4 py-2">Counterparty Risk</td>
                      <td className="border border-border px-4 py-2">Lending platforms, preferred share issuers, and stablecoin protocols may fail or default. Scores do not prevent such events.</td>
                      <td className="border border-border px-4 py-2">Structural quality assessment as of verified date. Not a guarantee of solvency.</td>
                    </tr>
                    <tr>
                      <td className="border border-border px-4 py-2">Regulatory Risk</td>
                      <td className="border border-border px-4 py-2">Regulatory status of digital asset platforms may change rapidly. Scored platforms may cease operations following regulatory action.</td>
                      <td className="border border-border px-4 py-2">Jurisdiction scores reflect published registration as of evidence review date.</td>
                    </tr>
                    <tr>
                      <td className="border border-border px-4 py-2">Liquidity Risk</td>
                      <td className="border border-border px-4 py-2">The ability to exit positions may be limited, especially under market stress.</td>
                      <td className="border border-border px-4 py-2">C4 Liquidity criterion specifically scores redemption architecture.</td>
                    </tr>
                    <tr>
                      <td className="border border-border px-4 py-2">Smart Contract Risk</td>
                      <td className="border border-border px-4 py-2">DeFi protocols involve code that may contain exploitable vulnerabilities. Audits do not guarantee security.</td>
                      <td className="border border-border px-4 py-2">C3 Counterparty/Protocol Risk assesses audit quality. Exploit history triggers maximum penalty.</td>
                    </tr>
                    <tr>
                      <td className="border border-border px-4 py-2">Data &amp; Methodology Risk</td>
                      <td className="border border-border px-4 py-2">Scores are computed from public data which may be incomplete or lagged. Methodology changes may alter scores materially.</td>
                      <td className="border border-border px-4 py-2">Evidence dates displayed on all scores. Material changes reviewed within 30 days.</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">7. Subscription, Billing, and Refund Policy</h2>
              <h3 className="mt-4 text-lg font-medium text-text-primary">7.1 Billing</h3>
              <ul className="mt-2 list-disc space-y-1 pl-6 text-text-secondary">
                <li>Subscription fees are billed in advance of each billing period (monthly or annual, as selected).</li>
                <li>All fees are quoted and charged in USD unless otherwise agreed in an Enterprise Services Agreement.</li>
                <li>Payment is due immediately upon subscription initiation and at each renewal date.</li>
                <li>The Company uses PCI-DSS compliant third-party payment processors. Full card data is never stored by the Company.</li>
                <li>Unpaid invoices beyond 14 days may result in suspension of Platform access.</li>
              </ul>
              <h3 className="mt-4 text-lg font-medium text-text-primary">7.2 Non-Refundability</h3>
              <p className="mt-2 text-text-secondary">
                All fees are non-refundable except where: (a) required by Applicable Law; (b) the Company materially fails to deliver subscribed features for a continuous period exceeding 72 hours due to causes within the Company&apos;s control; or (c) expressly agreed in writing in an Enterprise Services Agreement.
              </p>
              <h3 className="mt-4 text-lg font-medium text-text-primary">7.3 Auto-Renewal</h3>
              <p className="mt-2 text-text-secondary">
                Subscriptions automatically renew at the end of each billing period unless cancelled at least 48 hours before the renewal date. The Company may modify pricing with 30 days&apos; written notice; continued use after the notice period constitutes acceptance.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">8. Service Availability</h2>
              <p className="mt-2 text-text-secondary">
                The Company targets 99.0% monthly availability excluding scheduled maintenance. No guarantee of uninterrupted or error-free access is given. The Platform is provided on an &apos;as-available&apos; basis. Scheduled maintenance is communicated at least 24 hours in advance. Force Majeure Events suspend the Company&apos;s performance obligations.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">9. Intellectual Property</h2>
              <p className="mt-2 text-text-secondary">
                All methodologies, scoring systems, algorithms, source code, platform content, DCC Scores, trademarks, and documentation remain the exclusive property of the Company, protected under applicable intellectual property and trade secret law including UAE Federal Decree-Law No. 36 of 2021 on Trade Secrets.
              </p>
              <p className="mt-3 text-text-secondary">
                Users receive a limited, non-exclusive, non-transferable licence to access Platform outputs for their own internal informational purposes only. This licence does not permit bulk copying, redistribution, resale, white-labelling, reverse-engineering of the scoring algorithm, or use in any commercial product without written authorisation.
              </p>
              <div className="mt-4 rounded-lg border border-border bg-surface-elevated px-4 py-3 text-sm">
                <strong className="text-text-primary">TRADE SECRET PROTECTION</strong>
                <p className="mt-2 text-text-secondary">
                  The specific numerical weights, sub-criteria scoring tables, and formula parameters constituting the DCC Scoring Engine are trade secrets. Unauthorised disclosure or misappropriation constitutes a breach of these Terms and may give rise to civil liability and criminal prosecution under applicable trade secret law.
                </p>
              </div>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">10. Limitation of Liability</h2>
              <h3 className="mt-4 text-lg font-medium text-text-primary">10.1 Exclusion of Indirect Loss</h3>
              <p className="mt-2 text-text-secondary">
                To the maximum extent permitted by Applicable Law, the Company shall not be liable for any indirect, consequential, incidental, special, punitive, or exemplary loss, including loss of profit, revenue, opportunity, data, or goodwill, howsoever caused.
              </p>
              <h3 className="mt-4 text-lg font-medium text-text-primary">10.2 Exclusion of Investment Losses</h3>
              <p className="mt-2 text-text-secondary">
                The Company shall not be liable for any financial loss arising from any investment, capital allocation, or trading decision made in reliance on Platform outputs, regardless of whether such reliance was reasonable or foreseeable.
              </p>
              <h3 className="mt-4 text-lg font-medium text-text-primary">10.3 Liability Cap</h3>
              <p className="mt-2 text-text-secondary">
                The Company&apos;s aggregate liability to any User shall not exceed the greater of: (a) total fees paid by that User in the 12-month period preceding the event giving rise to liability; or (b) USD 500. Nothing herein limits liability for death or personal injury caused by negligence, fraud, or liability that cannot be excluded under Applicable Law.
              </p>
              <div className="mt-4 overflow-x-auto">
                <table className="min-w-full border-collapse border border-border text-sm">
                  <thead>
                    <tr className="bg-surface-elevated">
                      <th className="border border-border px-4 py-2 text-left font-semibold text-text-primary">Claim Type</th>
                      <th className="border border-border px-4 py-2 text-left font-semibold text-text-primary">Liability Position</th>
                    </tr>
                  </thead>
                  <tbody className="text-text-secondary">
                    <tr><td className="border border-border px-4 py-2">Investment / trading losses</td><td className="border border-border px-4 py-2">EXCLUDED</td></tr>
                    <tr><td className="border border-border px-4 py-2">Loss of opportunity / indirect damages</td><td className="border border-border px-4 py-2">EXCLUDED</td></tr>
                    <tr><td className="border border-border px-4 py-2">Direct loss from material scoring error attributable to DCC</td><td className="border border-border px-4 py-2">Capped at 12 months&apos; fees or USD 500 (whichever is greater)</td></tr>
                    <tr><td className="border border-border px-4 py-2">Death / personal injury / fraud</td><td className="border border-border px-4 py-2">NOT EXCLUDED — full liability retained</td></tr>
                  </tbody>
                </table>
              </div>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">11. Indemnification</h2>
              <p className="mt-2 text-text-secondary">
                The User agrees to indemnify, defend, and hold harmless the Company and its officers, directors, employees, agents, and service providers from and against all claims, losses, damages, costs (including legal costs), and expenses arising from: breach of these Terms; violation of Applicable Law; misuse of the Platform or DCC outputs; false representations; or infringement of third-party intellectual property rights in connection with use of the Platform.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">12. Enterprise Clients</h2>
              <p className="mt-2 text-text-secondary">
                Enterprise Clients are subject to additional terms under a separately executed Enterprise Services Agreement (ESA), which prevails over these general Terms in case of conflict. Enterprise onboarding requires completion of the Company&apos;s Know-Your-Business (KYB) and Anti-Money Laundering (AML) due diligence process. Enterprise Clients represent and warrant that their use of DCC outputs in their own products or services complies with all Applicable Law in each jurisdiction of operation.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">13. Regulatory Positioning</h2>
              <p className="mt-2 text-text-secondary">
                DCC is not authorised or regulated by the FCA (UK), SEC (USA), MAS (Singapore), ESMA (EU), or any other financial services regulatory body as at the Effective Date. The Company&apos;s current regulatory status — including any VARA (UAE) licensing — is published on its website and updated as changes occur. Users in regulated jurisdictions are responsible for determining whether access to and use of the Platform is permissible under their local regulatory framework.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">14. Termination</h2>
              <h3 className="mt-4 text-lg font-medium text-text-primary">14.1 By the User</h3>
              <p className="mt-2 text-text-secondary">
                Users may terminate access at any time by cancelling their subscription via account settings. Termination does not entitle the User to a refund of prepaid fees except as provided in Section 7.
              </p>
              <h3 className="mt-4 text-lg font-medium text-text-primary">14.2 By the Company</h3>
              <p className="mt-2 text-text-secondary">
                The Company may immediately suspend or terminate access, without prior notice and without liability, upon breach of these Terms, suspected fraudulent or illegal use, legal or regulatory necessity, non-payment, or a Force Majeure Event making continued provision unviable.
              </p>
              <h3 className="mt-4 text-lg font-medium text-text-primary">14.3 Survival</h3>
              <p className="mt-2 text-text-secondary">
                Sections 9 (IP), 10 (Liability), 11 (Indemnification), and 16 (Governing Law) survive termination.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">15. Amendments</h2>
              <p className="mt-2 text-text-secondary">
                The Company may amend these Terms at any time. Material amendments will be notified to Subscribers via email at least 14 days before they take effect. Continued use of the Platform following the effective date constitutes acceptance. Enterprise Clients are subject to the amendment provisions in their ESA.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">16. Governing Law and Dispute Resolution</h2>
              <p className="mt-2 text-text-secondary">
                The applicable governing law and dispute resolution mechanism depend on the User&apos;s jurisdiction:
              </p>
              <div className="mt-4 overflow-x-auto">
                <table className="min-w-full border-collapse border border-border text-sm">
                  <thead>
                    <tr className="bg-surface-elevated">
                      <th className="border border-border px-4 py-2 text-left font-semibold text-text-primary">User / Entity Type</th>
                      <th className="border border-border px-4 py-2 text-left font-semibold text-text-primary">Governing Law</th>
                      <th className="border border-border px-4 py-2 text-left font-semibold text-text-primary">Dispute Forum</th>
                    </tr>
                  </thead>
                  <tbody className="text-text-secondary">
                    <tr><td className="border border-border px-4 py-2">UAE / GCC (non-DIFC)</td><td className="border border-border px-4 py-2">UAE Federal and Emirate law</td><td className="border border-border px-4 py-2">Arbitration (DIAC) or UAE courts at Company&apos;s election</td></tr>
                    <tr><td className="border border-border px-4 py-2">DIFC-registered entities</td><td className="border border-border px-4 py-2">DIFC Law</td><td className="border border-border px-4 py-2">DIFC Courts</td></tr>
                    <tr><td className="border border-border px-4 py-2">UK / EEA Users</td><td className="border border-border px-4 py-2">English law</td><td className="border border-border px-4 py-2">Courts of England and Wales (non-exclusive)</td></tr>
                    <tr><td className="border border-border px-4 py-2">US Users</td><td className="border border-border px-4 py-2">Laws of the State of Delaware, USA</td><td className="border border-border px-4 py-2">Binding arbitration — JAMS rules, New York seat</td></tr>
                    <tr><td className="border border-border px-4 py-2">Singapore / APAC Users</td><td className="border border-border px-4 py-2">Singapore law</td><td className="border border-border px-4 py-2">Singapore International Arbitration Centre (SIAC)</td></tr>
                    <tr><td className="border border-border px-4 py-2">All Enterprise Clients</td><td className="border border-border px-4 py-2">As specified in executed ESA</td><td className="border border-border px-4 py-2">As specified in executed ESA</td></tr>
                  </tbody>
                </table>
              </div>
              <p className="mt-4 text-text-secondary">
                Nothing in this Section prevents either party from seeking urgent injunctive relief in any competent court to protect intellectual property or confidential information.
              </p>
            </section>
          </div>

          <p className="mt-10 border-t border-border pt-6 text-center text-xs text-text-muted">
            Not Investment Advice · Not a Regulated Financial Service · Digital Credit Compass
          </p>
          <div className="mt-6 flex justify-center">
            <Link
              href="/"
              className="text-sm font-medium text-[var(--primary)] hover:underline"
            >
              ← Back to home
            </Link>
          </div>
        </div>
      </main>
      <LandingFooter />
    </div>
  );
}
