import type { Metadata } from "next";
import Link from "next/link";
import { LandingHeader } from "@/components/landing/LandingHeader";
import { LandingFooter } from "@/components/landing/LandingFooter";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: "Disclaimer applicable to all Digital Credit Compass (DCC) scores, outputs, reports, and platform content.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-surface-base">
      <LandingHeader />
      <main className="mx-auto max-w-4xl px-4 py-12 sm:px-6 sm:py-16">
        <div className="rounded-xl border border-border bg-surface-card p-6 shadow-sm sm:p-8 lg:p-10">
          <header className="border-b border-border pb-6">
            <h1 className="font-heading text-3xl font-bold text-text-primary sm:text-4xl">
              Disclaimer
            </h1>
            <p className="mt-2 text-lg text-text-secondary">
              Applicable to All Digital Credit Compass (DCC) Scores, Outputs, Reports, and Platform Content
            </p>
          </header>

          <div className="prose prose-sm mt-8 max-w-none prose-headings:font-heading prose-headings:font-semibold prose-headings:text-text-primary prose-p:text-text-secondary prose-li:text-text-secondary prose-strong:text-text-primary">
            <div className="mb-8 rounded-lg border border-risk-mid bg-risk-mid-bg px-4 py-3 text-sm">
              <strong className="text-text-primary">IMPORTANT NOTICE — READ BEFORE PROCEEDING</strong>
              <p className="mt-2 text-text-secondary">
                This Disclaimer applies to every Risk Analysis Report, DCC Score, scenario output, yield estimate, risk band classification, Scenario Risk Index value, and any other content generated by the DCC platform. It constitutes a legally binding term of your use of the Platform and must be read in full before placing any reliance on any DCC output. These are not hortatory statements — they are substantive legal terms.
              </p>
            </div>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">1. Nature of Outputs — Not Financial Advice</h2>
              <p className="mt-2 text-text-secondary">
                All DCC outputs — including risk scores, score band classifications, Scenario Risk Index values, Reference Scenario (Illustrative) allocations, yield estimates, income projections, collateral calculations, and liquidation price thresholds — are analytical information produced by a deterministic algorithm applied to publicly available data.
              </p>
              <p className="mt-3 text-text-secondary">
                DCC outputs are <strong>NOT</strong>:
              </p>
              <ul className="mt-2 list-disc space-y-1 pl-6 text-text-secondary">
                <li>Investment advice, investment recommendations, or personalised financial advice of any kind;</li>
                <li>Regulated financial promotions, prospectuses, or offering documents;</li>
                <li>Credit ratings or credit opinions within the meaning of Regulation (EC) 1060/2009 (EU CRA Regulation), UK CRA Regulation, or any equivalent;</li>
                <li>Suitability assessments or appropriateness assessments under MiFID II, FCA COBS, MAS Notice SFA, or any equivalent;</li>
                <li>Actuarial assessments, risk management certifications, or compliance opinions.</li>
              </ul>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">2. Illustrative Outputs</h2>
              <p className="mt-2 text-text-secondary">
                The Reference Scenario (Illustrative) and all associated yield estimates, income projections, and allocation weights are illustrative benchmarks generated by the DCC scoring engine based on model parameters. They represent what a hypothetical investor with fully informed inputs might experience under the assumptions embedded in the model. Actual outcomes <strong>WILL</strong> differ materially from illustrative outputs. These outputs are scenario analyses only.
              </p>
              <p className="mt-3 text-text-secondary">
                The User Scenario (My Scenario) is constructed entirely from user-supplied inputs. The Company bears no responsibility for the accuracy or appropriateness of user-supplied assumptions, and the resulting outputs are the User&apos;s sole responsibility.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">3. Data Basis and Limitations</h2>
              <p className="mt-2 text-text-secondary">
                DCC Scores are computed solely from publicly available information as of the evidence review date displayed on each score. The Company does <strong>NOT</strong>: conduct independent audits of the financial statements or custody arrangements of platforms it scores; access private issuer data, non-public regulatory filings, or confidential management information; or verify the accuracy of self-reported information published by scored platforms.
              </p>
              <p className="mt-3 text-text-secondary">
                Where publicly available data is incomplete, contradictory, or absent, scores reflect available evidence only. The absence of data about a scored entity may itself be a negative risk indicator, reflected in applicable scoring penalties.
              </p>
              <p className="mt-3 text-text-secondary">
                Market data is sourced from third-party providers (Nasdaq Data Link, Yahoo Finance API, Polygon.io, CoinGecko, CoinMarketCap, DeFiLlama, and official regulatory registries). The Company makes commercially reasonable efforts to use reliable data sources but does not guarantee accuracy, completeness, or timeliness. API failures result in a &apos;Data Under Review&apos; status — Users must not rely on scores in this state.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">4. Past Performance</h2>
              <div className="mt-4 rounded-lg border border-border bg-surface-elevated px-4 py-3 text-sm">
                <strong className="text-text-primary">PAST PERFORMANCE WARNING</strong>
                <p className="mt-2 text-text-secondary">
                  Past DCC Scores, historical yield data, track records, prior methodology versions, and historical score band classifications do <strong>NOT</strong> predict, guarantee, or suggest future scoring outcomes, investment performance, yield levels, or platform behaviour. The digital asset sector is characterised by rapid structural change. Past performance is explicitly not a reliable indicator of future results.
                </p>
              </div>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">5. Third-Party Platform Risk</h2>
              <p className="mt-2 text-text-secondary">
                DCC is not responsible for the conduct, solvency, regulatory compliance, or operational decisions of any platform, issuer, or protocol whose products appear on the Platform. A DCC Score is a structural analysis based on publicly available information. It is not an endorsement, warranty, or guarantee of any kind in respect of the scored entity. The Company holds no financial interest in any instrument, provider, or allocation shown in any Platform output.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">6. Independence and No Conflicts of Interest</h2>
              <p className="mt-2 text-text-secondary">
                The Company does not accept payment from, and has no commercial relationship with, any provider, issuer, or platform in connection with the production or modification of any DCC Score. No score is influenced by commercial relationships or issuer-paid engagement. All scores are computed deterministically from publicly available information only.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">7. Methodology Versioning</h2>
              <p className="mt-2 text-text-secondary">
                Every DCC Score carries a permanent reference to the Methodology version under which it was computed. The Score Methodology is published in full at{" "}
                <a href="https://digitalcreditcompass.com/methodology" className="text-[var(--primary)] hover:underline" target="_blank" rel="noopener noreferrer">digitalcreditcompass.com/methodology</a>
                . Scores produced under prior versions remain valid and permanently retrievable. Any methodology change requires formal CRO approval and 30 days&apos; public advance notice.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">8. Jurisdiction-Specific Regulatory Notices</h2>

              <h3 className="mt-4 text-lg font-medium text-text-primary">UNITED KINGDOM</h3>
              <p className="mt-2 text-text-secondary">
                This document has not been approved by a person authorised under the Financial Services and Markets Act 2000 (FSMA). It is not a financial promotion within the meaning of section 21 FSMA and is not directed at retail clients within the meaning of the FCA&apos;s COBS rules. UK Users must seek independent regulated financial advice before acting on any DCC output.
              </p>

              <h3 className="mt-4 text-lg font-medium text-text-primary">UNITED STATES</h3>
              <p className="mt-2 text-text-secondary">
                DCC is not registered as an investment adviser under the Investment Advisers Act of 1940, a broker-dealer under the Securities Exchange Act of 1934, or a nationally recognised statistical rating organisation (NRSRO). DCC outputs are not investment advice within the meaning of US securities laws. US Persons must seek advice from a registered investment adviser before acting on DCC outputs.
              </p>

              <h3 className="mt-4 text-lg font-medium text-text-primary">EUROPEAN UNION</h3>
              <p className="mt-2 text-text-secondary">
                DCC is not authorised under MiFID II/MiFIR, AIFMD, or Regulation (EU) 2023/1114 (MiCA). DCC outputs do not constitute investment advice or crypto-asset advice within the meaning of EU financial services law. EU Users must seek independent regulated advice.
              </p>

              <h3 className="mt-4 text-lg font-medium text-text-primary">SINGAPORE</h3>
              <p className="mt-2 text-text-secondary">
                DCC is not licensed under the Securities and Futures Act (SFA) or the Financial Advisers Act (FAA) of Singapore. DCC outputs are not investment advice or financial advisory services regulated by the Monetary Authority of Singapore. Singapore Users must consult a MAS-licensed financial adviser.
              </p>

              <h3 className="mt-4 text-lg font-medium text-text-primary">UNITED ARAB EMIRATES</h3>
              <p className="mt-2 text-text-secondary">
                DCC operates within the UAE&apos;s virtual asset regulatory framework and is pursuing applicable licensing under the Virtual Assets Regulatory Authority (VARA). Pending any such licence becoming effective, DCC does not hold a licence to provide regulated financial services in the UAE. UAE Users should seek advice from a VARA-licensed or SCA-licensed provider as appropriate.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-text-primary">9. Liability</h2>
              <p className="mt-2 text-text-secondary">
                To the maximum extent permitted by Applicable Law, the Company shall not be liable for any loss arising from reliance on Platform outputs, including investment losses, loss of opportunity, or consequential damage. The Company&apos;s aggregate liability is capped as set out in the Terms and Conditions. Nothing herein limits liability for death or personal injury caused by negligence, or fraud.
              </p>
            </section>
          </div>

          <div className="mt-10 flex justify-center">
            <Link
              href="/"
              className="text-sm font-medium text-[var(--primary)] hover:underline"
            >
              ← Back to home
            </Link>
          </div>
        </div>
      </main>
      <LandingFooter />
    </div>
  );
}
